"""Strategy Discovery REST surface (PR-G2).

Endpoints:
  POST   /api/discovery/runs                — kick off a new discovery batch
  GET    /api/discovery/runs                — list past runs (most recent first)
  GET    /api/discovery/runs/{id}           — run detail + status
  GET    /api/discovery/runs/{id}/candidates— top candidates from a run
  GET    /api/discovery/candidates/{id}     — single candidate detail
  POST   /api/discovery/candidates/{id}/promote — promote to user_strategies
  POST   /api/discovery/candidates/{id}/archive — dismiss

The actual discovery work is offloaded to a background thread so the
POST returns immediately with the run id; clients poll via
``GET /runs/{id}`` for status. For a 30-candidate × 8-symbol equity_swing
run that's ~45-90 seconds of CPU; the runner persists progress so the
client always has *some* data to show even mid-run.

LOCKED: every candidate stored or promoted was generated by deterministic
search — never by an LLM. See project_agents_decision_2026_05_10.
"""

from __future__ import annotations

import logging
import threading
from datetime import datetime, timezone
from typing import Any, Dict, List, Optional
from uuid import UUID, uuid4

from fastapi import APIRouter, Depends, HTTPException, Query
from pydantic import BaseModel, Field, ValidationError

from ..ai.strategy.dsl import Strategy
from ..ai.strategy_discovery import DiscoveryConfig, run_discovery
from ..core.database import get_supabase_admin
from ..core.security import get_current_user

logger = logging.getLogger(__name__)

router = APIRouter(prefix="/api/discovery", tags=["Strategy Discovery"])


# Bounds on user-supplied input — tight enough that one user can't tie
# up the whole worker thread for hours.
MIN_SAMPLE_SIZE = 5
MAX_SAMPLE_SIZE = 60
MIN_SYMBOLS = 1
MAX_SYMBOLS = 20


# ─────────────────────────────────────────────────────────────────────
# Request / response shapes
# ─────────────────────────────────────────────────────────────────────


class CreateRunRequest(BaseModel):
    """User-facing payload to start a discovery run.

    Mirrors `DiscoveryConfig` but with stricter bounds so the worker
    can't be DoSed by a 10,000-sample request.
    """
    kind: str = Field(
        description=("equity_swing | equity_position | fo_weekly | fo_monthly"),
    )
    mode: str = Field(
        default="random",
        description=("`random` = sample_size random draws, fast/broad. "
                     "`ga` = elitist GA, pop_size × generations evaluations, "
                     "focused on near-best neighborhoods."),
    )
    sample_size: int = Field(default=20, ge=MIN_SAMPLE_SIZE, le=MAX_SAMPLE_SIZE)
    universe: str = Field(
        default="nifty50",
        description=("For equity: nifty50/100/500/250. For F&O: NIFTY|BANKNIFTY|FINNIFTY."),
    )
    symbols_per_candidate: int = Field(default=6, ge=MIN_SYMBOLS, le=MAX_SYMBOLS)
    history_period: str = Field(default="2y")
    seed: int = Field(default=42)

    # GA-mode knobs (ignored when mode='random')
    ga_pop_size: int = Field(default=12, ge=4, le=30)
    ga_generations: int = Field(default=3, ge=1, le=6)
    ga_elite: int = Field(default=4, ge=1, le=10)
    ga_children_per_elite: int = Field(default=2, ge=1, le=5)

    # Walk-forward — 0/1 disables. 3 = standard 3-fold (needs ~240 bars).
    walk_forward_folds: int = Field(default=0, ge=0, le=5)


class RunSummary(BaseModel):
    id: str
    kind: str
    status: str
    started_at: Optional[str]
    completed_at: Optional[str]
    candidates_total: int
    candidates_viable: int
    best_score: Optional[float]
    triggered_by_user_id: Optional[str]


class CandidateSummary(BaseModel):
    id: str
    run_id: str
    kind: str
    label: str
    score: float
    sharpe: Optional[float]
    calmar: Optional[float]
    max_drawdown_pct: Optional[float]
    win_rate: Optional[float]
    profit_factor: Optional[float]
    total_return_pct: Optional[float]
    trade_count: Optional[int]
    avg_hold_days: Optional[float]
    regime_scores: Dict[str, Any]
    status: str
    created_at: Optional[str]


class CandidateDetail(CandidateSummary):
    """Full candidate with DSL document — used on the promote review page."""
    dsl: Dict[str, Any]
    walk_forward: List[Dict[str, Any]]
    promoted_to_strategy_id: Optional[str]
    promoted_at: Optional[str]


class PromoteRequest(BaseModel):
    name: Optional[str] = Field(
        default=None, max_length=120,
        description=("Override the strategy name. Defaults to the candidate's name."),
    )
    mode: str = Field(
        default="paper",
        description=("paper | live — initial mode when copied to user_strategies"),
    )


# ─────────────────────────────────────────────────────────────────────
# Background worker — runs the discovery in a daemon thread.
# ─────────────────────────────────────────────────────────────────────


def _kick_off(cfg: DiscoveryConfig, user_id: Optional[UUID]) -> None:
    """Spawn the runner without blocking the request.

    The runner already handles all status persistence and error capture,
    so the caller doesn't need a return path — failures show up as
    `status='failed'` rows that the UI surfaces.
    """
    def _target():
        try:
            run_discovery(cfg, triggered_by_user_id=user_id)
        except Exception as e:
            logger.exception("background discovery failed: %s", e)

    t = threading.Thread(target=_target, name=f"discovery-{cfg.kind}", daemon=True)
    t.start()


# ─────────────────────────────────────────────────────────────────────
# Routes
# ─────────────────────────────────────────────────────────────────────


@router.post("/runs", status_code=201)
async def create_run(
    payload: CreateRunRequest,
    user=Depends(get_current_user),
) -> Dict[str, Any]:
    """Kick off a new discovery run. Returns immediately with the run id."""
    if payload.kind not in (
        "equity_swing", "equity_position",
        "fo_weekly", "fo_monthly",
        "intraday_5m", "intraday_15m",
    ):
        raise HTTPException(400, f"invalid kind: {payload.kind}")
    # F&O kinds require an index underlying, not a sector tier
    if payload.kind.startswith("fo_") and payload.universe.upper() not in (
        "NIFTY", "BANKNIFTY", "FINNIFTY",
    ):
        raise HTTPException(
            400, f"F&O discovery requires universe in NIFTY|BANKNIFTY|FINNIFTY, got {payload.universe}",
        )
    # Intraday: keep universe small (data heavy). Default to nifty50 if
    # caller picks an unsupported tier.
    if payload.kind.startswith("intraday_") and payload.universe not in (
        "nifty50", "nifty100",
    ):
        payload.universe = "nifty50"

    cfg = DiscoveryConfig(
        kind=payload.kind,
        mode=payload.mode,
        sample_size=payload.sample_size,
        universe=payload.universe,
        symbols_per_candidate=payload.symbols_per_candidate,
        history_period=payload.history_period,
        seed=payload.seed,
        ga_pop_size=payload.ga_pop_size,
        ga_generations=payload.ga_generations,
        ga_elite=payload.ga_elite,
        ga_children_per_elite=payload.ga_children_per_elite,
        walk_forward_folds=payload.walk_forward_folds,
    )

    # Insert a placeholder row immediately so the user gets a stable id
    # back to poll. The worker then runs `run_discovery(existing_run_id=…)`
    # which updates THIS row in place — no duplicate rows.
    sb = get_supabase_admin()
    placeholder = sb.table("strategy_search_runs").insert({
        "kind": payload.kind,
        "config": cfg.to_dict(),
        "status": "pending",
        "triggered_by_user_id": user.id if user else None,
    }).execute()
    placeholder_id = placeholder.data[0]["id"]

    def _target():
        try:
            from backend.ai.strategy_discovery import run_discovery
            run_discovery(cfg, existing_run_id=placeholder_id)
        except Exception as e:
            logger.exception("discovery worker failed: %s", e)
            # run_discovery already marks the row failed on exception

    threading.Thread(target=_target, name=f"discovery-{cfg.kind}", daemon=True).start()

    return {
        "run_id": placeholder_id,
        "status": "pending",
        "kind": payload.kind,
        "config": cfg.to_dict(),
    }


@router.get("/runs")
async def list_runs(
    kind: Optional[str] = Query(None),
    status: Optional[str] = Query(None),
    limit: int = Query(30, ge=1, le=100),
    user=Depends(get_current_user),
) -> Dict[str, List[Dict[str, Any]]]:
    """List recent runs — for the Discovered tab landing page."""
    sb = get_supabase_admin()
    q = sb.table("strategy_search_runs").select(
        "id,kind,status,started_at,completed_at,candidates_total,"
        "candidates_viable,best_score,triggered_by_user_id,error,created_at"
    )
    if kind:
        q = q.eq("kind", kind)
    if status:
        q = q.eq("status", status)
    q = q.order("created_at", desc=True).limit(limit)
    res = q.execute()
    return {"runs": res.data or []}


@router.get("/runs/{run_id}")
async def get_run(run_id: str, user=Depends(get_current_user)) -> Dict[str, Any]:
    sb = get_supabase_admin()
    res = sb.table("strategy_search_runs").select("*").eq("id", run_id).limit(1).execute()
    if not res.data:
        raise HTTPException(404, "run not found")
    return res.data[0]


@router.get("/runs/{run_id}/candidates")
async def list_candidates(
    run_id: str,
    limit: int = Query(20, ge=1, le=100),
    only_viable: bool = Query(True),
    user=Depends(get_current_user),
) -> Dict[str, List[Dict[str, Any]]]:
    """Top-K candidates for a run, sorted by score DESC."""
    sb = get_supabase_admin()
    q = sb.table("discovered_strategies").select(
        "id,run_id,kind,label,score,sharpe,calmar,max_drawdown_pct,"
        "win_rate,profit_factor,total_return_pct,trade_count,avg_hold_days,"
        "regime_scores,status,created_at"
    ).eq("run_id", run_id)
    if only_viable:
        q = q.eq("status", "candidate")
    q = q.order("score", desc=True).limit(limit)
    res = q.execute()
    return {"candidates": res.data or []}


@router.get("/candidates/{candidate_id}")
async def get_candidate(
    candidate_id: str,
    user=Depends(get_current_user),
) -> Dict[str, Any]:
    sb = get_supabase_admin()
    res = sb.table("discovered_strategies").select("*").eq("id", candidate_id).limit(1).execute()
    if not res.data:
        raise HTTPException(404, "candidate not found")
    return res.data[0]


@router.post("/candidates/{candidate_id}/promote")
async def promote_candidate(
    candidate_id: str,
    payload: PromoteRequest,
    user=Depends(get_current_user),
) -> Dict[str, Any]:
    """Copy the candidate's DSL into the user's strategy library.

    Creates a row in `user_strategies` referencing the discovered strategy.
    Validates the DSL through Strategy.model_validate first so we never
    write a malformed document.
    """
    sb = get_supabase_admin()

    # Load the candidate
    res = sb.table("discovered_strategies").select("*").eq("id", candidate_id).limit(1).execute()
    if not res.data:
        raise HTTPException(404, "candidate not found")
    cand = res.data[0]
    if cand["status"] != "candidate":
        raise HTTPException(
            400, f"candidate is already {cand['status']} — only `candidate` rows can be promoted",
        )

    # Validate DSL
    try:
        strategy = Strategy.model_validate(cand["dsl"])
    except ValidationError as e:
        raise HTTPException(400, f"candidate DSL failed validation: {e}")

    # Optional name override
    name = payload.name or cand.get("label") or strategy.name
    if payload.mode not in ("paper", "live"):
        raise HTTPException(400, "mode must be paper|live")

    # Insert into user_strategies
    new_strategy_id = str(uuid4())
    dsl_doc = strategy.model_dump(mode="json")
    dsl_doc["name"] = name
    dsl_doc["mode"] = payload.mode
    user_strategy_row = {
        "id": new_strategy_id,
        "user_id": user.id,
        "name": name[:120],
        "dsl": dsl_doc,
        "mode": payload.mode,
        "source": "discovery",
        "source_ref": candidate_id,
    }
    sb.table("user_strategies").insert(user_strategy_row).execute()

    # Mark the candidate as promoted
    sb.table("discovered_strategies").update({
        "status": "promoted",
        "promoted_to_strategy_id": new_strategy_id,
        "promoted_at": datetime.now(timezone.utc).isoformat(),
        "promoted_by_user_id": user.id,
    }).eq("id", candidate_id).execute()

    return {
        "promoted": True,
        "candidate_id": candidate_id,
        "user_strategy_id": new_strategy_id,
        "mode": payload.mode,
    }


@router.post("/candidates/{candidate_id}/archive")
async def archive_candidate(
    candidate_id: str,
    user=Depends(get_current_user),
) -> Dict[str, Any]:
    """Soft-archive a candidate — hides it from the leaderboard but keeps
    the row for audit / re-promote later."""
    sb = get_supabase_admin()
    res = sb.table("discovered_strategies").update({
        "status": "archived",
    }).eq("id", candidate_id).execute()
    if not res.data:
        raise HTTPException(404, "candidate not found")
    return {"archived": True, "candidate_id": candidate_id}
