#!/usr/bin/env python3
"""
P1-6: rebuild ``complete_schema.sql`` to be cumulative across all
post-base PR migrations.

Approach (Option B — non-destructive):
  * Keep ``infrastructure/database/migrations/`` with the per-PR
    files unchanged. Existing dev/staging databases that already
    applied them keep tracking via ``schema_migrations``.
  * The single ``complete_schema.sql`` file becomes a true
    ONE-FILE fresh-install path: existing 28-table base schema
    PLUS every post-base PR migration concatenated in chronological
    order.
  * All PR migrations use ``IF NOT EXISTS`` / ``ADD COLUMN IF NOT
    EXISTS``, so re-running them on a fresh-installed (already-
    cumulative) DB is a safe no-op.

Outputs ``complete_schema.sql`` with:
    Part A (existing): base 28-table schema
    Part B (rewritten on every run): concatenated PR migrations.

The Part-B boundary is marked with sentinel comments so this script
is idempotent — a second run regenerates Part B without touching
Part A.
"""

from __future__ import annotations

import sys
from pathlib import Path
from typing import List


REPO_ROOT = Path(__file__).resolve().parents[2]
MIGRATIONS_DIR = REPO_ROOT / "infrastructure" / "database" / "migrations"
CONSOLIDATED = REPO_ROOT / "infrastructure" / "database" / "complete_schema.sql"

PART_B_HEADER = "-- ============================================================================\n" \
                "-- PART B — POST-BASE PR MIGRATIONS (auto-generated, do not edit by hand)\n" \
                "-- ============================================================================\n" \
                "-- Regenerated by scripts/ops/consolidate_schema.py from the per-PR files in\n" \
                "-- infrastructure/database/migrations/. Edits made here will be overwritten.\n" \
                "--\n" \
                "-- This section makes ``complete_schema.sql`` a true one-file fresh-install:\n" \
                "-- Part A (above) creates the base 28-table schema; Part B applies every\n" \
                "-- post-base PR migration in chronological order. All migrations use\n" \
                "-- IF NOT EXISTS guards so re-application is a no-op.\n" \
                "--\n" \
                "-- Existing deployments that have already applied per-PR files via the\n" \
                "-- ``schema_migrations`` tracker do NOT re-run this — they continue using\n" \
                "-- the migration directory directly.\n" \
                "-- ============================================================================\n"

PART_B_FOOTER = "-- ============================================================================\n" \
                "-- END PART B — POST-BASE PR MIGRATIONS\n" \
                "-- ============================================================================\n"

# Files to skip (the schema_migrations bootstrap is run separately).
SKIP_FILES = {"000_schema_migrations.sql"}


def list_migrations() -> List[Path]:
    files = [
        p for p in MIGRATIONS_DIR.iterdir()
        if p.name.endswith(".sql") and p.name not in SKIP_FILES
    ]
    # Chronological order: filename starts with YYYY_MM_DD which sorts.
    files.sort(key=lambda p: p.name)
    return files


def build_part_b() -> str:
    files = list_migrations()
    chunks: List[str] = [PART_B_HEADER]
    for f in files:
        text = f.read_text(encoding="utf-8").rstrip()
        chunks.append(f"\n-- ──────────────────────────────────────────────────")
        chunks.append(f"-- Migration: {f.name}")
        chunks.append(f"-- ──────────────────────────────────────────────────\n")
        chunks.append(text)
        chunks.append("")  # blank line between files
    chunks.append(PART_B_FOOTER)
    return "\n".join(chunks)


def regenerate() -> None:
    current = CONSOLIDATED.read_text(encoding="utf-8")
    sentinel_start = "-- PART B — POST-BASE PR MIGRATIONS"
    if sentinel_start in current:
        # Re-run: replace existing Part B.
        idx = current.index("-- ============================================================================\n"
                            "-- PART B")
        part_a = current[:idx].rstrip() + "\n\n"
    else:
        # First run: append.
        part_a = current.rstrip() + "\n\n"

    new_text = part_a + build_part_b() + "\n"
    CONSOLIDATED.write_text(new_text, encoding="utf-8")
    print(f"Wrote {CONSOLIDATED}")
    files = list_migrations()
    print(f"  Part B includes {len(files)} PR migrations:")
    for f in files:
        print(f"    - {f.name}")


if __name__ == "__main__":
    regenerate()
