#!/usr/bin/env python
"""
PR-H: seed Strategy DSL templates into strategy_catalog.

Two groups:

A. UPDATE 6 existing equity_swing rows — replace legacy default_params
   with a real Strategy DSL document so users get a working backtest
   on first click.

B. INSERT 10 NEW beginner-friendly classic templates:
     1. RSI Mean Reversion (Nifty 50)
     2. EMA Golden Cross (Nifty 100)
     3. MACD Momentum
     4. Bollinger Bounce
     5. VWAP Pullback Intraday
     6. Trend + Pullback Daily
     7. Breakout + Volume
     8. Vision-Verdict Consensus (engine-driven)
     9. Alpha Top-10 Ranker (engine-driven)
    10. Mood Reversal Sentiment

Plus a CATALOG of Dhan-inspired options strategies (61) flagged with
`engine_compatible=False, dsl=NULL` — they stay as METADATA only until
the DSL is extended to multi-leg options (PR-J in a future cycle).

Idempotent: UPSERTs on slug, safe to re-run.

Usage::

    python scripts/ops/seed_strategy_dsl_templates.py
"""

from __future__ import annotations

import json
import logging
import sys
from pathlib import Path
from typing import Any, Dict, List

sys.path.insert(0, str(Path(__file__).resolve().parent.parent.parent))

from dotenv import load_dotenv
load_dotenv()

from backend.ai.strategy.dsl import Strategy  # noqa: E402
from backend.core.database import get_supabase_admin  # noqa: E402

logging.basicConfig(level=logging.INFO, format="%(asctime)s %(levelname)s: %(message)s")
logger = logging.getLogger("seed_dsl")


# ─────────────────────────────────────────────────────────────────────
# DSL TEMPLATES
# Each tuple: (slug, name, description, category, segment, tier, dsl, min_capital, risk_level, tags, engine_compatible)
# ─────────────────────────────────────────────────────────────────────


TEMPLATES: List[Dict[str, Any]] = [
    # ── A. UPDATE EXISTING equity_swing rows (slug must match) ──────
    {
        "slug": "consolidation-breakout",
        "name": "Consolidation Breakout",
        "description": "Buy when price breaks above 20-day high with above-average volume after a tight range.",
        "category": "equity_swing",
        "segment": "EQUITY",
        "tier_required": "free",
        "min_capital": 50_000,
        "risk_level": "medium",
        "tags": ["breakout", "volume", "swing", "beginner"],
        "engine_compatible": False,
        "dsl": {
            "name": "Consolidation Breakout",
            "universe": "nifty100",
            "timeframe": "1d",
            "entry": {
                "kind": "composite_and",
                "children": [
                    {"kind": "indicator_compare", "indicator": "close", "op": ">", "value": "sma20"},
                    {"kind": "indicator_compare", "indicator": "close", "op": ">", "value": "ema50"},
                    {"kind": "indicator_compare", "indicator": "volume_sma20", "op": ">", "value": 0},
                ],
            },
            "exit": {
                "kind": "composite_or",
                "children": [
                    {"kind": "indicator_compare", "indicator": "close", "op": "<", "value": "sma20"},
                    {"kind": "indicator_compare", "indicator": "rsi14", "op": ">", "value": 78},
                ],
            },
            "stop_loss_pct": 4,
            "take_profit_pct": 10,
            "position_size": {"kind": "percent_of_capital", "value": 5},
            "regime_filter": "any",
            "lookback_days": 180,
            "mode": "backtest",
        },
    },
    {
        "slug": "gap-and-go",
        "name": "Gap-and-Go Continuation",
        "description": "Event-driven: buy when price gaps above yesterday's high on expanding volume and holds green. Exit if the gap fills or RSI runs hot.",
        "category": "equity_swing",
        "segment": "EQUITY",
        "tier_required": "free",
        "min_capital": 50_000,
        "risk_level": "high",
        "tags": ["gap", "event-driven", "momentum", "volume"],
        "engine_compatible": False,
        "dsl": {
            "name": "Gap-and-Go Continuation",
            "universe": "nifty100",
            "timeframe": "1d",
            "entry": {
                "kind": "composite_and",
                "children": [
                    {"kind": "indicator_compare", "indicator": "open", "op": ">", "value": "prev_high"},
                    {"kind": "indicator_compare", "indicator": "close", "op": ">", "value": "open"},
                    {"kind": "indicator_compare", "indicator": "volume_ratio", "op": ">", "value": 1.5},
                ],
            },
            "exit": {
                "kind": "composite_or",
                "children": [
                    {"kind": "indicator_compare", "indicator": "close", "op": "<", "value": "prev_close"},
                    {"kind": "indicator_compare", "indicator": "rsi14", "op": ">", "value": 80},
                ],
            },
            "stop_loss_pct": 3,
            "take_profit_pct": 7,
            "position_size": {"kind": "percent_of_capital", "value": 4},
            "regime_filter": "any",
            "lookback_days": 180,
            "mode": "backtest",
        },
    },
    {
        "slug": "flow-confirmed-breakout",
        "name": "Flow-Confirmed Breakout",
        "description": "Order-flow family: buy an uptrend only when on-balance-volume is rising, net signed volume is positive and volume is expanding — breakout confirmed by accumulation, not price alone. Exit when flow turns distributive.",
        "category": "equity_swing",
        "segment": "EQUITY",
        "tier_required": "pro",
        "min_capital": 50_000,
        "risk_level": "medium",
        "tags": ["order-flow", "volume", "obv", "breakout"],
        "engine_compatible": False,
        "dsl": {
            "name": "Flow-Confirmed Breakout",
            "universe": "nifty100",
            "timeframe": "1d",
            "entry": {
                "kind": "composite_and",
                "children": [
                    {"kind": "indicator_compare", "indicator": "close", "op": ">", "value": "ema21"},
                    {"kind": "indicator_compare", "indicator": "obv_slope", "op": ">", "value": 0},
                    {"kind": "indicator_compare", "indicator": "volume_delta_20", "op": ">", "value": 0},
                    {"kind": "indicator_compare", "indicator": "volume_ratio", "op": ">", "value": 1.3},
                ],
            },
            "exit": {
                "kind": "composite_or",
                "children": [
                    {"kind": "indicator_compare", "indicator": "obv_slope", "op": "<", "value": 0},
                    {"kind": "indicator_compare", "indicator": "close", "op": "<", "value": "ema21"},
                ],
            },
            "stop_loss_pct": 4,
            "take_profit_pct": 9,
            "position_size": {"kind": "percent_of_capital", "value": 5},
            "regime_filter": "bull_only",
            "lookback_days": 180,
            "mode": "backtest",
        },
    },
    {
        "slug": "trend-pullback",
        "name": "Trend Pullback",
        "description": "Buy on a pullback to EMA20 in a confirmed uptrend (EMA50 > EMA200). Exit on EMA20 break or RSI overbought.",
        "category": "equity_swing",
        "segment": "EQUITY",
        "tier_required": "free",
        "min_capital": 50_000,
        "risk_level": "medium",
        "tags": ["trend", "pullback", "swing", "beginner"],
        "engine_compatible": False,
        "dsl": {
            "name": "Trend Pullback",
            "universe": "nifty100",
            "timeframe": "1d",
            "entry": {
                "kind": "composite_and",
                "children": [
                    {"kind": "indicator_compare", "indicator": "ema50", "op": ">", "value": "ema200"},
                    {"kind": "indicator_compare", "indicator": "close", "op": "<", "value": "ema21"},
                    {"kind": "indicator_compare", "indicator": "rsi14", "op": "between", "value": [38, 55]},
                ],
            },
            "exit": {
                "kind": "composite_or",
                "children": [
                    {"kind": "indicator_compare", "indicator": "close", "op": "<", "value": "ema50"},
                    {"kind": "indicator_compare", "indicator": "rsi14", "op": ">", "value": 75},
                ],
            },
            "stop_loss_pct": 3,
            "take_profit_pct": 8,
            "position_size": {"kind": "percent_of_capital", "value": 5},
            "regime_filter": "bull_only",
            "lookback_days": 180,
            "mode": "backtest",
        },
    },
    {
        "slug": "candle-reversal",
        "name": "Candle Reversal",
        "description": "Buy on hammer/bullish-engulfing at support (close above EMA50). Exit on opposite reversal or RSI overbought.",
        "category": "equity_swing",
        "segment": "EQUITY",
        "tier_required": "free",
        "min_capital": 50_000,
        "risk_level": "medium",
        "tags": ["candle-pattern", "reversal", "swing", "beginner"],
        "engine_compatible": False,
        "dsl": {
            "name": "Candle Reversal",
            "universe": "nifty100",
            "timeframe": "1d",
            "entry": {
                "kind": "composite_and",
                "children": [
                    {"kind": "indicator_compare", "indicator": "close", "op": ">", "value": "ema50"},
                    {
                        "kind": "composite_or",
                        "children": [
                            {"kind": "indicator_compare", "indicator": "pattern_hammer", "op": "==", "value": 1},
                            {"kind": "indicator_compare", "indicator": "pattern_bullish_engulfing", "op": "==", "value": 1},
                            {"kind": "indicator_compare", "indicator": "pattern_morning_star", "op": "==", "value": 1},
                        ],
                    },
                ],
            },
            "exit": {
                "kind": "composite_or",
                "children": [
                    {"kind": "indicator_compare", "indicator": "pattern_bearish_engulfing", "op": "==", "value": 1},
                    {"kind": "indicator_compare", "indicator": "rsi14", "op": ">", "value": 72},
                ],
            },
            "stop_loss_pct": 3,
            "take_profit_pct": 7,
            "position_size": {"kind": "percent_of_capital", "value": 4},
            "regime_filter": "any",
            "lookback_days": 180,
            "mode": "backtest",
        },
    },
    {
        "slug": "bos-structure",
        "name": "BOS Structure",
        "description": "Break-of-structure entry: buy when price crosses above the 20-bar high after pulling back to EMA21.",
        "category": "equity_swing",
        "segment": "EQUITY",
        "tier_required": "free",
        "min_capital": 50_000,
        "risk_level": "high",
        "tags": ["price-action", "swing", "intermediate"],
        "engine_compatible": False,
        "dsl": {
            "name": "BOS Structure",
            "universe": "nifty100",
            "timeframe": "1d",
            "entry": {
                "kind": "composite_and",
                "children": [
                    {"kind": "indicator_cross", "indicator": "close", "op": "crosses_above", "value": "ema21"},
                    {"kind": "indicator_compare", "indicator": "adx", "op": ">", "value": 20},
                ],
            },
            "exit": {"kind": "indicator_cross", "indicator": "close", "op": "crosses_below", "value": "ema21"},
            "stop_loss_pct": 4,
            "take_profit_pct": 12,
            "position_size": {"kind": "percent_of_capital", "value": 4},
            "regime_filter": "any",
            "lookback_days": 180,
            "mode": "backtest",
        },
    },
    {
        "slug": "reversal-patterns",
        "name": "Reversal Patterns",
        "description": "Multi-pattern reversal scanner: morning star, hammer, or three-white-soldiers near a moving average. ATR-sized stops.",
        "category": "equity_swing",
        "segment": "EQUITY",
        "tier_required": "free",
        "min_capital": 50_000,
        "risk_level": "medium",
        "tags": ["candle-pattern", "reversal", "swing"],
        "engine_compatible": False,
        "dsl": {
            "name": "Reversal Patterns",
            "universe": "nifty100",
            "timeframe": "1d",
            "entry": {
                "kind": "composite_and",
                "children": [
                    {
                        "kind": "composite_or",
                        "children": [
                            {"kind": "indicator_compare", "indicator": "pattern_morning_star", "op": "==", "value": 1},
                            {"kind": "indicator_compare", "indicator": "pattern_hammer", "op": "==", "value": 1},
                            {"kind": "indicator_compare", "indicator": "pattern_three_white_soldiers", "op": "==", "value": 1},
                        ],
                    },
                    {"kind": "indicator_compare", "indicator": "rsi14", "op": "<", "value": 45},
                ],
            },
            "exit": {
                "kind": "composite_or",
                "children": [
                    {"kind": "indicator_compare", "indicator": "rsi14", "op": ">", "value": 65},
                    {"kind": "indicator_compare", "indicator": "pattern_evening_star", "op": "==", "value": 1},
                    {"kind": "indicator_compare", "indicator": "pattern_three_black_crows", "op": "==", "value": 1},
                ],
            },
            "stop_loss_pct": 4,
            "take_profit_pct": 10,
            "position_size": {"kind": "percent_of_capital", "value": 4},
            "regime_filter": "any",
            "lookback_days": 180,
            "mode": "backtest",
        },
    },
    {
        "slug": "volume-reversal",
        "name": "Volume Reversal",
        "description": "Heavy volume + bullish reversal candle near a moving average, indicating institutional accumulation.",
        "category": "equity_swing",
        "segment": "EQUITY",
        "tier_required": "free",
        "min_capital": 50_000,
        "risk_level": "medium",
        "tags": ["volume", "wyckoff", "swing", "intermediate"],
        "engine_compatible": False,
        "dsl": {
            "name": "Volume Reversal",
            "universe": "nifty100",
            "timeframe": "1d",
            "entry": {
                "kind": "composite_and",
                "children": [
                    {"kind": "indicator_compare", "indicator": "pattern_bullish_engulfing", "op": "==", "value": 1},
                    {"kind": "indicator_compare", "indicator": "close", "op": ">", "value": "sma50"},
                    {"kind": "indicator_compare", "indicator": "rsi14", "op": "<", "value": 60},
                ],
            },
            "exit": {
                "kind": "composite_or",
                "children": [
                    {"kind": "indicator_compare", "indicator": "rsi14", "op": ">", "value": 70},
                    {"kind": "indicator_compare", "indicator": "close", "op": "<", "value": "ema21"},
                ],
            },
            "stop_loss_pct": 3,
            "take_profit_pct": 8,
            "position_size": {"kind": "percent_of_capital", "value": 5},
            "regime_filter": "any",
            "lookback_days": 180,
            "mode": "backtest",
        },
    },
    # ── B. NEW beginner-friendly classic templates ──────────────────
    {
        "slug": "rsi-mean-reversion",
        "name": "RSI Mean Reversion",
        "description": "The classic oversold bounce. Buy when RSI(14) drops below 30 on stocks above their long-term trend. Sell when RSI crosses 70.",
        "category": "equity_swing",
        "segment": "EQUITY",
        "tier_required": "free",
        "min_capital": 25_000,
        "risk_level": "low",
        "tags": ["beginner", "rsi", "mean-reversion", "classic"],
        "is_featured": True,
        "engine_compatible": False,
        "dsl": {
            "name": "RSI Mean Reversion",
            "universe": "nifty100",
            "timeframe": "1d",
            "entry": {
                "kind": "composite_and",
                "children": [
                    {"kind": "indicator_compare", "indicator": "rsi14", "op": "<", "value": 30},
                    {"kind": "indicator_compare", "indicator": "close", "op": ">", "value": "ema200"},
                ],
            },
            "exit": {"kind": "indicator_compare", "indicator": "rsi14", "op": ">", "value": 70},
            "stop_loss_pct": 4,
            "take_profit_pct": 8,
            "position_size": {"kind": "percent_of_capital", "value": 5},
            "regime_filter": "any",
            "lookback_days": 180,
            "mode": "backtest",
        },
    },
    {
        "slug": "ema-golden-cross",
        "name": "EMA Golden Cross",
        "description": "The most famous trend signal: enter when EMA50 crosses above EMA200, exit on the reverse cross. Captures multi-month trends with one rule each side.",
        "category": "equity_swing",
        "segment": "EQUITY",
        "tier_required": "free",
        "min_capital": 50_000,
        "risk_level": "low",
        "tags": ["beginner", "trend", "golden-cross", "classic"],
        "is_featured": True,
        "engine_compatible": False,
        "dsl": {
            "name": "EMA Golden Cross",
            "universe": "nifty100",
            "timeframe": "1d",
            "entry": {"kind": "indicator_cross", "indicator": "ema50", "op": "crosses_above", "value": "ema200"},
            "exit": {"kind": "indicator_cross", "indicator": "ema50", "op": "crosses_below", "value": "ema200"},
            "stop_loss_pct": 6,
            "take_profit_pct": 25,
            "trailing_stop_pct": 8,
            "position_size": {"kind": "percent_of_capital", "value": 6},
            "regime_filter": "any",
            "lookback_days": 365,
            "mode": "backtest",
        },
    },
    {
        "slug": "macd-momentum",
        "name": "MACD Momentum",
        "description": "Catch momentum shifts: enter when MACD crosses above its signal line in an uptrend (close > EMA50). Exit on opposite cross.",
        "category": "equity_swing",
        "segment": "EQUITY",
        "tier_required": "free",
        "min_capital": 30_000,
        "risk_level": "medium",
        "tags": ["beginner", "momentum", "macd"],
        "engine_compatible": False,
        "dsl": {
            "name": "MACD Momentum",
            "universe": "nifty100",
            "timeframe": "1d",
            "entry": {
                "kind": "composite_and",
                "children": [
                    {"kind": "indicator_cross", "indicator": "macd", "op": "crosses_above", "value": "macd_signal"},
                    {"kind": "indicator_compare", "indicator": "close", "op": ">", "value": "ema50"},
                ],
            },
            "exit": {"kind": "indicator_cross", "indicator": "macd", "op": "crosses_below", "value": "macd_signal"},
            "stop_loss_pct": 4,
            "take_profit_pct": 10,
            "position_size": {"kind": "percent_of_capital", "value": 5},
            "regime_filter": "any",
            "lookback_days": 180,
            "mode": "backtest",
        },
    },
    {
        "slug": "bollinger-bounce",
        "name": "Bollinger Bounce",
        "description": "Buy when price tags the lower Bollinger Band in an uptrend (above EMA200). Sell at the middle band (SMA20).",
        "category": "equity_swing",
        "segment": "EQUITY",
        "tier_required": "free",
        "min_capital": 30_000,
        "risk_level": "medium",
        "tags": ["beginner", "bollinger", "mean-reversion"],
        "engine_compatible": False,
        "dsl": {
            "name": "Bollinger Bounce",
            "universe": "nifty100",
            "timeframe": "1d",
            "entry": {
                "kind": "composite_and",
                "children": [
                    {"kind": "indicator_compare", "indicator": "close", "op": "<", "value": "bbands_lower"},
                    {"kind": "indicator_compare", "indicator": "close", "op": ">", "value": "ema200"},
                ],
            },
            "exit": {"kind": "indicator_compare", "indicator": "close", "op": ">", "value": "bbands_middle"},
            "stop_loss_pct": 3,
            "take_profit_pct": 6,
            "position_size": {"kind": "percent_of_capital", "value": 4},
            "regime_filter": "any",
            "lookback_days": 180,
            "mode": "backtest",
        },
    },
    {
        "slug": "vwap-pullback-intraday",
        "name": "VWAP Pullback Intraday",
        "description": "5-min intraday: buy pullbacks to VWAP in an early trend with RSI > 50. Tight 1% stop, 2% target. Square-off by close.",
        "category": "equity_swing",
        "segment": "EQUITY",
        "tier_required": "pro",
        "min_capital": 50_000,
        "risk_level": "high",
        "tags": ["intraday", "vwap", "scalping"],
        "engine_compatible": False,
        "dsl": {
            "name": "VWAP Pullback Intraday",
            "universe": "nifty50",
            "timeframe": "5m",
            "entry": {
                "kind": "composite_and",
                "children": [
                    {"kind": "indicator_compare", "indicator": "close", "op": ">", "value": "vwap"},
                    {"kind": "indicator_compare", "indicator": "rsi14", "op": "between", "value": [45, 60]},
                ],
            },
            "exit": {
                "kind": "composite_or",
                "children": [
                    {"kind": "indicator_compare", "indicator": "close", "op": "<", "value": "vwap"},
                    {"kind": "indicator_compare", "indicator": "rsi14", "op": ">", "value": 72},
                ],
            },
            "stop_loss_pct": 1,
            "take_profit_pct": 2,
            "position_size": {"kind": "percent_of_capital", "value": 5},
            "regime_filter": "any",
            "lookback_days": 60,
            "mode": "backtest",
        },
    },
    {
        "slug": "supertrend-trail",
        "name": "SuperTrend Trail",
        "description": "Beginner-friendly trend rider. Enter when close crosses above SuperTrend, ride until close crosses back below. Built-in trailing.",
        "category": "equity_swing",
        "segment": "EQUITY",
        "tier_required": "free",
        "min_capital": 30_000,
        "risk_level": "medium",
        "tags": ["beginner", "trend", "supertrend"],
        "engine_compatible": False,
        "dsl": {
            "name": "SuperTrend Trail",
            "universe": "nifty100",
            "timeframe": "1d",
            "entry": {"kind": "indicator_cross", "indicator": "close", "op": "crosses_above", "value": "supertrend"},
            "exit": {"kind": "indicator_cross", "indicator": "close", "op": "crosses_below", "value": "supertrend"},
            "stop_loss_pct": 5,
            "take_profit_pct": 20,
            "position_size": {"kind": "percent_of_capital", "value": 5},
            "regime_filter": "any",
            "lookback_days": 180,
            "mode": "backtest",
        },
    },
    {
        "slug": "alpha-regime-consensus",
        "name": "Alpha-Regime Consensus",
        "description": "Engine-driven: enter top-decile Qlib Alpha ranks ONLY in a bull HMM regime. Exit when stock falls outside top-25 or regime flips bear.",
        "category": "equity_swing",
        "segment": "EQUITY",
        "tier_required": "pro",
        "min_capital": 50_000,
        "risk_level": "medium",
        "tags": ["ai", "engine-driven", "consensus", "alpha", "regime"],
        "is_featured": True,
        "engine_compatible": True,
        "dsl": {
            "name": "Alpha-Regime Consensus",
            "universe": "nifty100",
            "timeframe": "1d",
            "entry": {
                "kind": "composite_and",
                "children": [
                    {"kind": "engine_signal", "engine": "Alpha",  "op": "<=", "value": 10},
                    {"kind": "engine_signal", "engine": "Regime", "op": "==", "value": "bull"},
                ],
            },
            "exit": {
                "kind": "composite_or",
                "children": [
                    {"kind": "engine_signal", "engine": "Alpha",  "op": ">", "value": 25},
                    {"kind": "engine_signal", "engine": "Regime", "op": "==", "value": "bear"},
                ],
            },
            "stop_loss_pct": 4,
            "take_profit_pct": 10,
            "position_size": {"kind": "percent_of_capital", "value": 5},
            "regime_filter": "bull_only",
            "lookback_days": 90,
            "mode": "backtest",
        },
    },
    {
        "slug": "alpha-top10-ranker",
        "name": "Alpha Top-10 Ranker",
        "description": "Buy the day's top-10 Alpha (Qlib LightGBM) picks, sized 1% each. Exit when rank drops below top 30.",
        "category": "equity_swing",
        "segment": "EQUITY",
        "tier_required": "pro",
        "min_capital": 100_000,
        "risk_level": "medium",
        "tags": ["ai", "engine-driven", "ranker", "cross-sectional"],
        "is_featured": True,
        "engine_compatible": True,
        "dsl": {
            "name": "Alpha Top-10 Ranker",
            "universe": "nifty100",
            "timeframe": "1d",
            "entry": {"kind": "engine_signal", "engine": "Alpha", "op": "<=", "value": 10},
            "exit": {"kind": "engine_signal", "engine": "Alpha", "op": ">", "value": 30},
            "stop_loss_pct": 5,
            "take_profit_pct": 15,
            "position_size": {"kind": "percent_of_capital", "value": 1},
            "regime_filter": "any",
            "lookback_days": 90,
            "mode": "backtest",
        },
    },
    {
        "slug": "mood-reversal-sentiment",
        "name": "Mood Reversal Sentiment",
        "description": "Buy stocks where the Mood engine's news sentiment flipped strongly positive in the last 5 days and price confirms with RSI > 50.",
        "category": "equity_swing",
        "segment": "EQUITY",
        "tier_required": "pro",
        "min_capital": 50_000,
        "risk_level": "medium",
        "tags": ["ai", "sentiment", "engine-driven", "news"],
        "engine_compatible": True,
        "dsl": {
            "name": "Mood Reversal Sentiment",
            "universe": "nifty100",
            "timeframe": "1d",
            "entry": {
                "kind": "composite_and",
                "children": [
                    {"kind": "engine_signal", "engine": "Mood", "op": ">", "value": 0.3},
                    {"kind": "indicator_compare", "indicator": "rsi14", "op": ">", "value": 50},
                    {"kind": "indicator_compare", "indicator": "close", "op": ">", "value": "ema50"},
                ],
            },
            "exit": {
                "kind": "composite_or",
                "children": [
                    {"kind": "engine_signal", "engine": "Mood", "op": "<", "value": 0.0},
                    {"kind": "indicator_compare", "indicator": "rsi14", "op": ">", "value": 75},
                ],
            },
            "stop_loss_pct": 4,
            "take_profit_pct": 12,
            "position_size": {"kind": "percent_of_capital", "value": 4},
            "regime_filter": "any",
            "lookback_days": 90,
            "mode": "backtest",
        },
    },
    {
        "slug": "regime-aware-trend",
        "name": "Regime-Aware Trend",
        "description": "Enter EMA8/EMA21 crossovers ONLY when the HMM Regime engine reports 'bull'. Built-in bear protection.",
        "category": "equity_swing",
        "segment": "EQUITY",
        "tier_required": "free",
        "min_capital": 50_000,
        "risk_level": "low",
        "tags": ["beginner", "regime-aware", "ai", "trend"],
        "is_featured": True,
        "engine_compatible": True,
        "dsl": {
            "name": "Regime-Aware Trend",
            "universe": "nifty100",
            "timeframe": "1d",
            "entry": {"kind": "indicator_cross", "indicator": "ema8", "op": "crosses_above", "value": "ema21"},
            "exit": {"kind": "indicator_cross", "indicator": "ema8", "op": "crosses_below", "value": "ema21"},
            "stop_loss_pct": 4,
            "take_profit_pct": 12,
            "position_size": {"kind": "percent_of_capital", "value": 5},
            "regime_filter": "bull_only",
            "lookback_days": 180,
            "mode": "backtest",
        },
    },
    # ────────────────────────────────────────────────────────────
    # PR-J multi-leg options templates
    # All are weekly index options (NIFTY/BANKNIFTY).
    # ────────────────────────────────────────────────────────────
    {
        "slug": "iron-condor-nifty-weekly",
        "name": "Iron Condor — NIFTY Weekly",
        "description": "Range-bound thesis: sell premium on both wings. Defined risk via long protective strikes. Fires when Regime engine reports sideways.",
        "category": "options_selling",
        "segment": "OPTIONS",
        "template_slug": "options_credit_spread",
        "tier_required": "elite",
        "min_capital": 150_000,
        "risk_level": "medium",
        "tags": ["options", "credit-spread", "neutral", "weekly", "defined-risk"],
        "is_featured": True,
        "engine_compatible": True,
        "dsl": {
            "name": "Iron Condor — NIFTY Weekly",
            "instrument_segment": "OPTIONS",
            "symbol": "NIFTY",
            "universe": "single",
            "timeframe": "1d",
            "entry": {"kind": "engine_signal", "engine": "Regime", "op": "==", "value": "sideways"},
            "exit": {"kind": "engine_signal", "engine": "Regime", "op": "!=", "value": "sideways"},
            "stop_loss_pct": 50,
            "take_profit_pct": 60,
            "position_size": {"kind": "percent_of_capital", "value": 20},
            "legs": [
                {"side": "sell", "option_type": "PE", "strike_anchor": "ATM-N", "strike_offset": 2, "expiry": "current_week"},
                {"side": "buy",  "option_type": "PE", "strike_anchor": "ATM-N", "strike_offset": 4, "expiry": "current_week"},
                {"side": "sell", "option_type": "CE", "strike_anchor": "ATM+N", "strike_offset": 2, "expiry": "current_week"},
                {"side": "buy",  "option_type": "CE", "strike_anchor": "ATM+N", "strike_offset": 4, "expiry": "current_week"},
            ],
            "lookback_days": 365,
            "mode": "backtest",
        },
    },
    {
        "slug": "bull-call-spread-nifty",
        "name": "Bull Call Spread — NIFTY",
        "description": "Moderately bullish view with defined risk. Buy ATM call, sell OTM+2 call. Profit capped at the short strike.",
        "category": "options_buying",
        "segment": "OPTIONS",
        "template_slug": "options_debit_spread",
        "tier_required": "elite",
        "min_capital": 60_000,
        "risk_level": "low",
        "tags": ["options", "debit-spread", "bullish", "weekly", "defined-risk"],
        "is_featured": True,
        "engine_compatible": True,
        "dsl": {
            "name": "Bull Call Spread — NIFTY",
            "instrument_segment": "OPTIONS",
            "symbol": "NIFTY",
            "universe": "single",
            "timeframe": "1d",
            "entry": {"kind": "engine_signal", "engine": "Regime", "op": "==", "value": "bull"},
            "exit": {"kind": "engine_signal", "engine": "Regime", "op": "==", "value": "bear"},
            "stop_loss_pct": 50,
            "take_profit_pct": 80,
            "position_size": {"kind": "percent_of_capital", "value": 15},
            "legs": [
                {"side": "buy",  "option_type": "CE", "strike_anchor": "ATM",   "strike_offset": 0, "expiry": "current_week"},
                {"side": "sell", "option_type": "CE", "strike_anchor": "ATM+N", "strike_offset": 2, "expiry": "current_week"},
            ],
            "lookback_days": 365,
            "mode": "backtest",
        },
    },
    {
        "slug": "bear-put-spread-nifty",
        "name": "Bear Put Spread — NIFTY",
        "description": "Moderately bearish view with defined risk. Buy ATM put, sell OTM-2 put. Profit capped at the short strike.",
        "category": "options_buying",
        "segment": "OPTIONS",
        "template_slug": "options_debit_spread",
        "tier_required": "elite",
        "min_capital": 60_000,
        "risk_level": "low",
        "tags": ["options", "debit-spread", "bearish", "weekly", "defined-risk"],
        "is_featured": False,
        "engine_compatible": True,
        "dsl": {
            "name": "Bear Put Spread — NIFTY",
            "instrument_segment": "OPTIONS",
            "symbol": "NIFTY",
            "universe": "single",
            "timeframe": "1d",
            "entry": {"kind": "engine_signal", "engine": "Regime", "op": "==", "value": "bear"},
            "exit": {"kind": "engine_signal", "engine": "Regime", "op": "==", "value": "bull"},
            "stop_loss_pct": 50,
            "take_profit_pct": 80,
            "position_size": {"kind": "percent_of_capital", "value": 15},
            "legs": [
                {"side": "buy",  "option_type": "PE", "strike_anchor": "ATM",   "strike_offset": 0, "expiry": "current_week"},
                {"side": "sell", "option_type": "PE", "strike_anchor": "ATM-N", "strike_offset": 2, "expiry": "current_week"},
            ],
            "lookback_days": 365,
            "mode": "backtest",
        },
    },
    {
        "slug": "long-straddle-nifty-vol",
        "name": "Long Straddle — NIFTY (event vol)",
        "description": "Buy ATM call + ATM put. Profit on big moves either direction. Best around events (RBI, budget, earnings).",
        "category": "options_buying",
        "segment": "OPTIONS",
        "template_slug": "options_straddle",
        "tier_required": "elite",
        "min_capital": 80_000,
        "risk_level": "high",
        "tags": ["options", "straddle", "volatility", "event-driven", "weekly"],
        "is_featured": False,
        "engine_compatible": False,
        "dsl": {
            "name": "Long Straddle — NIFTY (event vol)",
            "instrument_segment": "OPTIONS",
            "symbol": "NIFTY",
            "universe": "single",
            "timeframe": "1d",
            "entry": {"kind": "indicator_compare", "indicator": "atr", "op": ">", "value": 100},
            "exit": {"kind": "indicator_compare", "indicator": "atr", "op": "<", "value": 50},
            "stop_loss_pct": 40,
            "take_profit_pct": 100,
            "position_size": {"kind": "percent_of_capital", "value": 10},
            "legs": [
                {"side": "buy", "option_type": "CE", "strike_anchor": "ATM", "strike_offset": 0, "expiry": "current_week"},
                {"side": "buy", "option_type": "PE", "strike_anchor": "ATM", "strike_offset": 0, "expiry": "current_week"},
            ],
            "lookback_days": 365,
            "mode": "backtest",
        },
    },
    {
        "slug": "short-strangle-banknifty",
        "name": "Short Strangle — BANKNIFTY Weekly",
        "description": "Aggressive premium-collection. Sell OTM call + OTM put. Undefined risk; requires margin and a hard stop. Bear regime locked out.",
        "category": "options_selling",
        "segment": "OPTIONS",
        "template_slug": "options_strangle",
        "tier_required": "elite",
        "min_capital": 300_000,
        "risk_level": "high",
        "tags": ["options", "strangle", "premium-selling", "undefined-risk", "weekly"],
        "is_featured": False,
        "engine_compatible": True,
        "dsl": {
            "name": "Short Strangle — BANKNIFTY Weekly",
            "instrument_segment": "OPTIONS",
            "symbol": "BANKNIFTY",
            "universe": "single",
            "timeframe": "1d",
            "entry": {"kind": "engine_signal", "engine": "Regime", "op": "==", "value": "sideways"},
            "exit": {"kind": "engine_signal", "engine": "Regime", "op": "!=", "value": "sideways"},
            "stop_loss_pct": 40,
            "take_profit_pct": 50,
            "position_size": {"kind": "percent_of_capital", "value": 25},
            "regime_filter": "sideways_only",
            "legs": [
                {"side": "sell", "option_type": "CE", "strike_anchor": "ATM+N", "strike_offset": 3, "expiry": "current_week"},
                {"side": "sell", "option_type": "PE", "strike_anchor": "ATM-N", "strike_offset": 3, "expiry": "current_week"},
            ],
            "lookback_days": 365,
            "mode": "backtest",
        },
    },
    {
        "slug": "iron-butterfly-nifty",
        "name": "Iron Butterfly — NIFTY",
        "description": "Maximum credit at ATM pin. Sell ATM straddle, buy protective wings ±2 strikes. Best when expecting low realized vol into expiry.",
        "category": "options_selling",
        "segment": "OPTIONS",
        "template_slug": "options_credit_spread",
        "tier_required": "elite",
        "min_capital": 200_000,
        "risk_level": "medium",
        "tags": ["options", "iron-butterfly", "neutral", "weekly", "defined-risk"],
        "is_featured": False,
        "engine_compatible": True,
        "dsl": {
            "name": "Iron Butterfly — NIFTY",
            "instrument_segment": "OPTIONS",
            "symbol": "NIFTY",
            "universe": "single",
            "timeframe": "1d",
            "entry": {"kind": "engine_signal", "engine": "Regime", "op": "==", "value": "sideways"},
            "exit": {"kind": "engine_signal", "engine": "Regime", "op": "!=", "value": "sideways"},
            "stop_loss_pct": 60,
            "take_profit_pct": 50,
            "position_size": {"kind": "percent_of_capital", "value": 15},
            "legs": [
                {"side": "sell", "option_type": "PE", "strike_anchor": "ATM",   "strike_offset": 0, "expiry": "current_week"},
                {"side": "sell", "option_type": "CE", "strike_anchor": "ATM",   "strike_offset": 0, "expiry": "current_week"},
                {"side": "buy",  "option_type": "PE", "strike_anchor": "ATM-N", "strike_offset": 2, "expiry": "current_week"},
                {"side": "buy",  "option_type": "CE", "strike_anchor": "ATM+N", "strike_offset": 2, "expiry": "current_week"},
            ],
            "lookback_days": 365,
            "mode": "backtest",
        },
    },
    # ────────────────────────────────────────────────────────────
    # PR-K FinStocks-inspired DSL templates
    #
    # Curated from the FinStocks public dashboard. Adapted to our DSL —
    # any indicator we don't yet support (P/E, ROI, promoter holding,
    # 52-week-high, opening-range) is skipped or substituted with the
    # closest momentum/volume proxy.
    #
    # Several flagged is_exclusive=True drive the "Exclusive Strategies"
    # section ("Unlock advanced algorithms for consistent performance.")
    # ────────────────────────────────────────────────────────────
    {
        "slug": "vwap-ema-momentum-breakout",
        "name": "VWAP + EMA Momentum Breakout",
        "description": "Buy Nifty 100 when price holds above VWAP and EMA8 trades above EMA21. Exit at 0.8% profit.",
        "category": "equity_intraday",
        "segment": "EQUITY",
        "tier_required": "free",
        "min_capital": 100_000,
        "risk_level": "medium",
        "tags": ["finstocks-inspired", "vwap", "ema", "momentum", "intraday", "beginner"],
        "is_featured": True,
        "engine_compatible": False,
        "dsl": {
            "name": "VWAP + EMA Momentum Breakout",
            "universe": "nifty100",
            "timeframe": "5m",
            "entry": {
                "kind": "composite_and",
                "children": [
                    {"kind": "indicator_compare", "indicator": "close", "op": ">", "value": "vwap"},
                    {"kind": "indicator_compare", "indicator": "ema8",  "op": ">", "value": "ema21"},
                ],
            },
            "exit": {"kind": "indicator_compare", "indicator": "ema8", "op": "<", "value": "ema21"},
            "stop_loss_pct": 0.5,
            "take_profit_pct": 0.8,
            "position_size": {"kind": "percent_of_capital", "value": 10},
            "lookback_days": 90,
            "mode": "backtest",
        },
    },
    {
        "slug": "rsi-pullback-uptrend",
        "name": "RSI Pullback in Uptrend",
        "description": "Buy when RSI(14) cools to 40-45 inside a 50-EMA uptrend. Exit when RSI > 60 or price loses the 50-EMA.",
        "category": "equity_swing",
        "segment": "EQUITY",
        "tier_required": "free",
        "min_capital": 50_000,
        "risk_level": "low",
        "tags": ["finstocks-inspired", "rsi", "pullback", "swing", "trend-following"],
        "is_featured": True,
        "engine_compatible": False,
        "dsl": {
            "name": "RSI Pullback in Uptrend",
            "universe": "nifty100",
            "timeframe": "1d",
            "entry": {
                "kind": "composite_and",
                "children": [
                    {"kind": "indicator_compare", "indicator": "rsi14", "op": "between", "value": [40, 45]},
                    {"kind": "indicator_compare", "indicator": "close", "op": ">", "value": "ema50"},
                ],
            },
            "exit": {
                "kind": "composite_or",
                "children": [
                    {"kind": "indicator_compare", "indicator": "rsi14", "op": ">", "value": 60},
                    {"kind": "indicator_compare", "indicator": "close", "op": "<", "value": "ema50"},
                ],
            },
            "stop_loss_pct": 3,
            "take_profit_pct": 8,
            "position_size": {"kind": "percent_of_capital", "value": 8},
            "lookback_days": 180,
            "mode": "backtest",
        },
    },
    {
        "slug": "ema50-reclaim-trend-strength",
        "name": "EMA50 Reclaim + Trend Strength",
        "description": "Catch the day a stock reclaims the 50-EMA inside a strong-trend regime (ADX > 25). Exit at 8% or 3% stop.",
        "category": "equity_swing",
        "segment": "EQUITY",
        "tier_required": "pro",
        "min_capital": 100_000,
        "risk_level": "medium",
        "tags": ["finstocks-inspired", "ema", "adx", "trend-following", "swing"],
        "is_featured": False,
        "engine_compatible": False,
        "dsl": {
            "name": "EMA50 Reclaim + Trend Strength",
            "universe": "nifty100",
            "timeframe": "1d",
            "entry": {
                "kind": "composite_and",
                "children": [
                    {"kind": "indicator_compare", "indicator": "low",   "op": "<", "value": "ema50"},
                    {"kind": "indicator_compare", "indicator": "close", "op": ">", "value": "ema50"},
                    {"kind": "indicator_compare", "indicator": "adx",   "op": ">", "value": 25},
                ],
            },
            "exit": {"kind": "indicator_compare", "indicator": "close", "op": "<", "value": "ema50"},
            "stop_loss_pct": 3,
            "take_profit_pct": 8,
            "position_size": {"kind": "percent_of_capital", "value": 10},
            "lookback_days": 180,
            "mode": "backtest",
        },
    },
    {
        "slug": "mfi-oversold-vwap-confluence",
        "name": "MFI Oversold + VWAP Confluence",
        "description": "Tight 4-filter intraday setup: MFI < 25, price above VWAP, EMA8 > EMA21, RSI > 35. Exit MFI > 60.",
        "category": "equity_intraday",
        "segment": "EQUITY",
        "tier_required": "pro",
        "min_capital": 100_000,
        "risk_level": "medium",
        "tags": ["finstocks-inspired", "mfi", "vwap", "intraday", "mean-reversion"],
        "is_featured": False,
        "engine_compatible": False,
        "is_exclusive": True,
        "exclusive_tagline": "Multi-filter intraday confluence — beats single-indicator signals",
        "dsl": {
            "name": "MFI Oversold + VWAP Confluence",
            "universe": "nifty100",
            "timeframe": "5m",
            "entry": {
                "kind": "composite_and",
                "children": [
                    {"kind": "indicator_compare", "indicator": "mfi",   "op": "<", "value": 25},
                    {"kind": "indicator_compare", "indicator": "close", "op": ">", "value": "vwap"},
                    {"kind": "indicator_compare", "indicator": "ema8",  "op": ">", "value": "ema21"},
                    {"kind": "indicator_compare", "indicator": "rsi14", "op": ">", "value": 35},
                ],
            },
            "exit": {"kind": "indicator_compare", "indicator": "mfi", "op": ">", "value": 60},
            "stop_loss_pct": 1.5,
            "take_profit_pct": 2,
            "position_size": {"kind": "percent_of_capital", "value": 8},
            "lookback_days": 60,
            "mode": "backtest",
        },
    },
    {
        "slug": "bollinger-lower-vwap-reversal",
        "name": "Bollinger Lower + VWAP Reversal",
        "description": "Buy bounces off the lower Bollinger band but only when price holds above VWAP and EMA8 > EMA21. Exit at the middle band.",
        "category": "equity_intraday",
        "segment": "EQUITY",
        "tier_required": "pro",
        "min_capital": 100_000,
        "risk_level": "medium",
        "tags": ["finstocks-inspired", "bollinger", "vwap", "mean-reversion", "intraday"],
        "is_featured": False,
        "engine_compatible": False,
        "dsl": {
            "name": "Bollinger Lower + VWAP Reversal",
            "universe": "nifty100",
            "timeframe": "5m",
            "entry": {
                "kind": "composite_and",
                "children": [
                    {"kind": "indicator_compare", "indicator": "close", "op": "<=", "value": "bbands_lower"},
                    {"kind": "indicator_compare", "indicator": "close", "op": ">",  "value": "vwap"},
                    {"kind": "indicator_compare", "indicator": "rsi14", "op": "<",  "value": 38},
                    {"kind": "indicator_compare", "indicator": "ema8",  "op": ">",  "value": "ema21"},
                ],
            },
            "exit": {"kind": "indicator_compare", "indicator": "close", "op": ">=", "value": "bbands_middle"},
            "stop_loss_pct": 1.5,
            "take_profit_pct": 2,
            "position_size": {"kind": "percent_of_capital", "value": 8},
            "lookback_days": 60,
            "mode": "backtest",
        },
    },
    {
        "slug": "rsi7-oversold-vwap-pullback",
        "name": "RSI7 Oversold + VWAP Pullback",
        "description": "Fast 7-period RSI oversold dip inside an intraday uptrend — VWAP support, EMA8>EMA21, ADX>18.",
        "category": "equity_intraday",
        "segment": "EQUITY",
        "tier_required": "pro",
        "min_capital": 100_000,
        "risk_level": "medium",
        "tags": ["finstocks-inspired", "rsi", "vwap", "intraday", "scalp"],
        "is_featured": False,
        "engine_compatible": False,
        "dsl": {
            "name": "RSI7 Oversold + VWAP Pullback",
            "universe": "nifty100",
            "timeframe": "5m",
            "entry": {
                "kind": "composite_and",
                "children": [
                    {"kind": "indicator_compare", "indicator": "rsi7",  "op": "<", "value": 28},
                    {"kind": "indicator_compare", "indicator": "close", "op": ">", "value": "vwap"},
                    {"kind": "indicator_compare", "indicator": "ema8",  "op": ">", "value": "ema21"},
                    {"kind": "indicator_compare", "indicator": "adx",   "op": ">", "value": 18},
                ],
            },
            "exit": {"kind": "indicator_compare", "indicator": "rsi7", "op": ">", "value": 62},
            "stop_loss_pct": 1.5,
            "take_profit_pct": 2,
            "position_size": {"kind": "percent_of_capital", "value": 8},
            "lookback_days": 60,
            "mode": "backtest",
        },
    },
    {
        "slug": "stochastic-oversold-bounce",
        "name": "Stochastic Oversold Bounce",
        "description": "Stoch K below 20 with bullish K>D crossover. Filters: above VWAP, EMA8>EMA21, RSI > 40.",
        "category": "equity_intraday",
        "segment": "EQUITY",
        "tier_required": "pro",
        "min_capital": 100_000,
        "risk_level": "medium",
        "tags": ["finstocks-inspired", "stochastic", "intraday", "bounce"],
        "is_featured": False,
        "engine_compatible": False,
        "dsl": {
            "name": "Stochastic Oversold Bounce",
            "universe": "nifty100",
            "timeframe": "5m",
            "entry": {
                "kind": "composite_and",
                "children": [
                    {"kind": "indicator_compare", "indicator": "stochastic_k", "op": "<", "value": 20},
                    {"kind": "indicator_compare", "indicator": "stochastic_k", "op": ">", "value": "stochastic_d"},
                    {"kind": "indicator_compare", "indicator": "close",        "op": ">", "value": "vwap"},
                    {"kind": "indicator_compare", "indicator": "ema8",         "op": ">", "value": "ema21"},
                ],
            },
            "exit": {"kind": "indicator_compare", "indicator": "stochastic_k", "op": ">", "value": 75},
            "stop_loss_pct": 1.5,
            "take_profit_pct": 2,
            "position_size": {"kind": "percent_of_capital", "value": 8},
            "lookback_days": 60,
            "mode": "backtest",
        },
    },
    {
        "slug": "williamsr-rsi-adx-trend",
        "name": "Williams %R + RSI + ADX Trend",
        "description": "Williams %R deeply oversold inside a 50/200-EMA bull cross + ADX > 20 trend strength.",
        "category": "equity_swing",
        "segment": "EQUITY",
        "tier_required": "pro",
        "min_capital": 100_000,
        "risk_level": "medium",
        "tags": ["finstocks-inspired", "williams-r", "rsi", "adx", "swing"],
        "is_featured": False,
        "engine_compatible": False,
        "is_exclusive": True,
        "exclusive_tagline": "Four-condition trend-confirmation with bull-cross filter",
        "dsl": {
            "name": "Williams %R + RSI + ADX Trend",
            "universe": "nifty100",
            "timeframe": "1d",
            "entry": {
                "kind": "composite_and",
                "children": [
                    {"kind": "indicator_compare", "indicator": "williams_r", "op": "<", "value": -70},
                    {"kind": "indicator_compare", "indicator": "ema50",      "op": ">", "value": "ema200"},
                    {"kind": "indicator_compare", "indicator": "adx",        "op": ">", "value": 20},
                    {"kind": "indicator_compare", "indicator": "rsi14",      "op": ">", "value": 38},
                ],
            },
            "exit": {"kind": "indicator_compare", "indicator": "williams_r", "op": ">", "value": -20},
            "stop_loss_pct": 5,
            "take_profit_pct": 8,
            "position_size": {"kind": "percent_of_capital", "value": 10},
            "lookback_days": 180,
            "mode": "backtest",
        },
    },
    {
        "slug": "supertrend-momentum-stack",
        "name": "SuperTrend Momentum Stack",
        "description": "Stacked trend confirmation: above SuperTrend + above EMA50 + ADX>22 + MACD positive.",
        "category": "equity_swing",
        "segment": "EQUITY",
        "tier_required": "pro",
        "min_capital": 100_000,
        "risk_level": "medium",
        "tags": ["finstocks-inspired", "supertrend", "macd", "adx", "swing", "stacked"],
        "is_featured": False,
        "engine_compatible": False,
        "is_exclusive": True,
        "exclusive_tagline": "Multi-indicator trend stack — high-conviction breakout filter",
        "dsl": {
            "name": "SuperTrend Momentum Stack",
            "universe": "nifty100",
            "timeframe": "1d",
            "entry": {
                "kind": "composite_and",
                "children": [
                    {"kind": "indicator_compare", "indicator": "close",     "op": ">", "value": "supertrend"},
                    {"kind": "indicator_compare", "indicator": "close",     "op": ">", "value": "ema50"},
                    {"kind": "indicator_compare", "indicator": "adx",       "op": ">", "value": 22},
                    {"kind": "indicator_compare", "indicator": "macd_hist", "op": ">", "value": 0},
                ],
            },
            "exit": {"kind": "indicator_compare", "indicator": "close", "op": "<", "value": "supertrend"},
            "stop_loss_pct": 4,
            "take_profit_pct": 10,
            "position_size": {"kind": "percent_of_capital", "value": 10},
            "lookback_days": 180,
            "mode": "backtest",
        },
    },
    {
        "slug": "macd-bullish-with-adx",
        "name": "MACD Bullish + ADX Filter",
        "description": "MACD crosses above signal line only when ADX confirms trend strength (>20).",
        "category": "equity_swing",
        "segment": "EQUITY",
        "tier_required": "free",
        "min_capital": 50_000,
        "risk_level": "low",
        "tags": ["finstocks-inspired", "macd", "adx", "swing", "trend-following"],
        "is_featured": False,
        "engine_compatible": False,
        "dsl": {
            "name": "MACD Bullish + ADX Filter",
            "universe": "nifty100",
            "timeframe": "1d",
            "entry": {
                "kind": "composite_and",
                "children": [
                    {"kind": "indicator_cross",   "indicator": "macd", "op": "crosses_above", "value": "macd_signal"},
                    {"kind": "indicator_compare", "indicator": "adx",  "op": ">",             "value": 20},
                ],
            },
            "exit": {"kind": "indicator_cross", "indicator": "macd", "op": "crosses_below", "value": "macd_signal"},
            "stop_loss_pct": 3,
            "take_profit_pct": 8,
            "position_size": {"kind": "percent_of_capital", "value": 8},
            "lookback_days": 180,
            "mode": "backtest",
        },
    },
    {
        "slug": "obv-momentum-confirmation",
        "name": "OBV Momentum Confirmation",
        "description": "Trend trades only when OBV agrees: close > EMA21 AND OBV rising over the prior 5 bars.",
        "category": "equity_swing",
        "segment": "EQUITY",
        "tier_required": "pro",
        "min_capital": 100_000,
        "risk_level": "medium",
        "tags": ["finstocks-inspired", "obv", "volume", "swing"],
        "is_featured": False,
        "engine_compatible": False,
        "dsl": {
            "name": "OBV Momentum Confirmation",
            "universe": "nifty100",
            "timeframe": "1d",
            "entry": {
                "kind": "composite_and",
                "children": [
                    {"kind": "indicator_compare", "indicator": "close", "op": ">", "value": "ema21"},
                    {"kind": "indicator_compare", "indicator": "obv",   "op": ">", "value": 0},
                ],
            },
            "exit": {"kind": "indicator_compare", "indicator": "close", "op": "<", "value": "ema21"},
            "stop_loss_pct": 3,
            "take_profit_pct": 7,
            "position_size": {"kind": "percent_of_capital", "value": 8},
            "lookback_days": 180,
            "mode": "backtest",
        },
    },
    {
        "slug": "regime-aware-autopilot-light",
        "name": "AutoPilot Lite — Regime-Aware Swing",
        "description": "Mirrors AutoPilot's PROD stack: top-15 Qlib Alpha rank + bull HMM regime + ADX>20 trend confirmation. Closest user-authorable form to the F4 executor.",
        "category": "equity_swing",
        "segment": "EQUITY",
        "tier_required": "elite",
        "min_capital": 200_000,
        "risk_level": "medium",
        "tags": ["finstocks-inspired", "autopilot", "multi-engine", "swing", "ai"],
        "is_featured": True,
        "engine_compatible": True,
        "is_exclusive": True,
        "exclusive_tagline": "Flagship engine-stack: mirrors AutoPilot's PROD consensus filter",
        "dsl": {
            "name": "AutoPilot Lite — Regime-Aware Swing",
            "universe": "nifty100",
            "timeframe": "1d",
            "entry": {
                "kind": "composite_and",
                "children": [
                    {"kind": "engine_signal",     "engine": "Alpha",  "op": "<=", "value": 15},
                    {"kind": "engine_signal",     "engine": "Regime", "op": "==", "value": "bull"},
                    {"kind": "indicator_compare", "indicator": "adx", "op": ">",  "value": 20},
                    {"kind": "indicator_compare", "indicator": "ema50", "op": ">", "value": "ema200"},
                ],
            },
            "exit": {
                "kind": "composite_or",
                "children": [
                    {"kind": "engine_signal",     "engine": "Alpha",  "op": ">",  "value": 35},
                    {"kind": "engine_signal",     "engine": "Regime", "op": "==", "value": "bear"},
                ],
            },
            "stop_loss_pct": 4,
            "take_profit_pct": 12,
            "trailing_stop_pct": 3,
            "position_size": {"kind": "percent_of_capital", "value": 12},
            "regime_filter": "bull_only",
            "lookback_days": 180,
            "mode": "backtest",
        },
    },
    {
        "slug": "alpha-rank-momentum-leader",
        "name": "Alpha Rank — Momentum Leader",
        "description": "Trade only the highest-ranked stock per the Alpha engine (Qlib). Tight EMA stack, ADX confirmation, weekly rebalance.",
        "category": "equity_swing",
        "segment": "EQUITY",
        "tier_required": "elite",
        "min_capital": 200_000,
        "risk_level": "medium",
        "tags": ["finstocks-inspired", "alpha", "ranker", "momentum", "engine"],
        "is_featured": True,
        "engine_compatible": True,
        "is_exclusive": True,
        "exclusive_tagline": "Engine-ranked selection — only the cream of NIFTY 100",
        "dsl": {
            "name": "Alpha Rank — Momentum Leader",
            "universe": "nifty100",
            "timeframe": "1d",
            "entry": {
                "kind": "composite_and",
                "children": [
                    {"kind": "engine_signal",     "engine": "Alpha", "op": "<=", "value": 5},
                    {"kind": "indicator_compare", "indicator": "ema8",  "op": ">", "value": "ema21"},
                    {"kind": "indicator_compare", "indicator": "ema21", "op": ">", "value": "ema50"},
                    {"kind": "indicator_compare", "indicator": "adx",   "op": ">", "value": 22},
                ],
            },
            "exit": {"kind": "engine_signal", "engine": "Alpha", "op": ">", "value": 25},
            "stop_loss_pct": 4,
            "take_profit_pct": 12,
            "position_size": {"kind": "percent_of_capital", "value": 12},
            "lookback_days": 180,
            "mode": "backtest",
        },
    },
    {
        "slug": "supertrend-vwap-intraday",
        "name": "SuperTrend + VWAP",
        "description": "Intraday trend trade: long when close > SuperTrend AND close > VWAP. Exit when SuperTrend flips bearish.",
        "category": "equity_intraday",
        "segment": "EQUITY",
        "tier_required": "free",
        "min_capital": 50_000,
        "risk_level": "medium",
        "tags": ["finstocks-inspired", "supertrend", "vwap", "intraday", "trend-following"],
        "is_featured": True,
        "engine_compatible": False,
        "dsl": {
            "name": "SuperTrend + VWAP",
            "universe": "nifty100",
            "timeframe": "5m",
            "entry": {
                "kind": "composite_and",
                "children": [
                    {"kind": "indicator_compare", "indicator": "close", "op": ">", "value": "supertrend"},
                    {"kind": "indicator_compare", "indicator": "close", "op": ">", "value": "vwap"},
                ],
            },
            "exit": {"kind": "indicator_compare", "indicator": "close", "op": "<", "value": "supertrend"},
            "stop_loss_pct": 1.0,
            "take_profit_pct": 1.5,
            "position_size": {"kind": "percent_of_capital", "value": 10},
            "lookback_days": 60,
            "mode": "backtest",
        },
    },
    {
        "slug": "ema-crossover-swing",
        "name": "EMA Crossover Swing",
        "description": "Buy Nifty 100 when (Price > VWAP) AND (EMA8 > EMA21), sell when 0.8% profit hit. Capital ₹100K, classic beginner template.",
        "category": "equity_swing",
        "segment": "EQUITY",
        "tier_required": "free",
        "min_capital": 100_000,
        "risk_level": "low",
        "tags": ["finstocks-inspired", "ema", "crossover", "swing", "beginner", "classic"],
        "is_featured": True,
        "engine_compatible": False,
        "dsl": {
            "name": "EMA Crossover Swing",
            "universe": "nifty100",
            "timeframe": "1d",
            "entry": {
                "kind": "composite_and",
                "children": [
                    {"kind": "indicator_compare", "indicator": "close", "op": ">", "value": "vwap"},
                    {"kind": "indicator_compare", "indicator": "ema8",  "op": ">", "value": "ema21"},
                ],
            },
            "exit": {"kind": "indicator_compare", "indicator": "ema8", "op": "<", "value": "ema21"},
            "stop_loss_pct": 2.0,
            "take_profit_pct": 0.8,
            "position_size": {"kind": "percent_of_capital", "value": 15},
            "lookback_days": 180,
            "mode": "backtest",
        },
    },
    {
        "slug": "ema-compression-breakout",
        "name": "EMA Compression Breakout",
        "description": "Buy when EMA21/EMA50/EMA100 are tightly clustered (proxy: close > all three with EMA21 > EMA50). Trade volatility expansion off compression.",
        "category": "equity_swing",
        "segment": "EQUITY",
        "tier_required": "pro",
        "min_capital": 100_000,
        "risk_level": "medium",
        "tags": ["finstocks-inspired", "ema", "compression", "breakout", "swing"],
        "is_featured": False,
        "engine_compatible": False,
        "is_exclusive": True,
        "exclusive_tagline": "Volatility-expansion breakout from a compressed EMA cluster",
        "dsl": {
            "name": "EMA Compression Breakout",
            "universe": "nifty100",
            "timeframe": "1d",
            "entry": {
                "kind": "composite_and",
                "children": [
                    {"kind": "indicator_compare", "indicator": "close", "op": ">", "value": "ema21"},
                    {"kind": "indicator_compare", "indicator": "ema21", "op": ">", "value": "ema50"},
                    {"kind": "indicator_compare", "indicator": "ema50", "op": ">", "value": "ema100"},
                    {"kind": "indicator_compare", "indicator": "adx",   "op": ">", "value": 20},
                ],
            },
            "exit": {"kind": "indicator_compare", "indicator": "close", "op": "<", "value": "ema100"},
            "stop_loss_pct": 3,
            "take_profit_pct": 10,
            "position_size": {"kind": "percent_of_capital", "value": 8},
            "lookback_days": 180,
            "mode": "backtest",
        },
    },
    {
        "slug": "mood-momentum-breakout",
        "name": "Mood Momentum Breakout",
        "description": "Catch sentiment-driven breakouts: Mood>0.3 + close above EMA21 + ADX>20 + RSI in healthy 50-70 zone. News-tape-driven entry with technical confirmation.",
        "category": "equity_swing",
        "segment": "EQUITY",
        "tier_required": "elite",
        "min_capital": 150_000,
        "risk_level": "high",
        "tags": ["finstocks-inspired", "mood", "sentiment", "swing", "ai"],
        "is_featured": False,
        "engine_compatible": True,
        "is_exclusive": True,
        "exclusive_tagline": "News-tape-driven momentum — pairs sentiment with technical confirmation",
        "dsl": {
            "name": "Mood Momentum Breakout",
            "universe": "nifty100",
            "timeframe": "1d",
            "entry": {
                "kind": "composite_and",
                "children": [
                    {"kind": "engine_signal",     "engine": "Mood",  "op": ">",  "value": 0.3},
                    {"kind": "indicator_compare", "indicator": "close", "op": ">", "value": "ema21"},
                    {"kind": "indicator_compare", "indicator": "adx",   "op": ">", "value": 20},
                    {"kind": "indicator_compare", "indicator": "rsi14", "op": "between", "value": [50, 70]},
                ],
            },
            "exit": {"kind": "engine_signal", "engine": "Mood", "op": "<", "value": -0.1},
            "stop_loss_pct": 4,
            "take_profit_pct": 10,
            "position_size": {"kind": "percent_of_capital", "value": 8},
            "lookback_days": 90,
            "mode": "backtest",
        },
    },
    # ────────────────────────────────────────────────────────────
    # PR-AS Micro-capital starter templates — entry-level retail
    # Designed for accounts in the ₹10-25K range. Single-symbol, low
    # share count, tight stops. NOT meant for portfolio-style allocation.
    # ────────────────────────────────────────────────────────────
    {
        "slug": "starter-single-stock-rsi",
        "name": "Starter — Single-Stock RSI",
        "description": "Buy 1-5 shares of a single NIFTY50 stock when RSI(14)<30 in a 50-EMA uptrend. Exit when RSI>60. Designed for accounts starting from ₹10K.",
        "category": "equity_swing",
        "segment": "EQUITY",
        "tier_required": "free",
        "min_capital": 10_000,
        "risk_level": "low",
        "tags": ["beginner", "starter", "micro-capital", "single-stock", "rsi", "classic"],
        "is_featured": True,
        "engine_compatible": False,
        "dsl": {
            "name": "Starter — Single-Stock RSI",
            "universe": "nifty50",
            "timeframe": "1d",
            "entry": {
                "kind": "composite_and",
                "children": [
                    {"kind": "indicator_compare", "indicator": "rsi14", "op": "<", "value": 30},
                    {"kind": "indicator_compare", "indicator": "close", "op": ">", "value": "ema50"},
                ],
            },
            "exit": {"kind": "indicator_compare", "indicator": "rsi14", "op": ">", "value": 60},
            "stop_loss_pct": 3,
            "take_profit_pct": 6,
            "position_size": {"kind": "percent_of_capital", "value": 25},
            "lookback_days": 180,
            "mode": "backtest",
        },
    },
    {
        "slug": "starter-etf-dip-buyer",
        "name": "Starter — ETF Dip Buyer",
        "description": "Buy NIFTYBEES (Nifty 50 ETF) when price drops to the lower Bollinger band with RSI<40. Exit at middle band. Single-symbol, low-risk, beginner-friendly. ₹15K minimum.",
        "category": "equity_swing",
        "segment": "EQUITY",
        "tier_required": "free",
        "min_capital": 15_000,
        "risk_level": "low",
        "tags": ["beginner", "starter", "micro-capital", "etf", "dip-buying", "low-risk"],
        "is_featured": True,
        "engine_compatible": False,
        "dsl": {
            "name": "Starter — ETF Dip Buyer",
            "symbol": "NIFTYBEES",
            "universe": "single",
            "timeframe": "1d",
            "entry": {
                "kind": "composite_and",
                "children": [
                    {"kind": "indicator_compare", "indicator": "close", "op": "<=", "value": "bbands_lower"},
                    {"kind": "indicator_compare", "indicator": "rsi14", "op": "<", "value": 40},
                ],
            },
            "exit": {"kind": "indicator_compare", "indicator": "close", "op": ">=", "value": "bbands_middle"},
            "stop_loss_pct": 4,
            "take_profit_pct": 6,
            "position_size": {"kind": "percent_of_capital", "value": 40},
            "lookback_days": 180,
            "mode": "backtest",
        },
    },
    {
        "slug": "starter-single-ema-trend",
        "name": "Starter — Single-EMA Trend Follow",
        "description": "Buy a NIFTY50 stock crossing back above EMA21 with ADX>20 trend strength. Exit on EMA21 break. Ideal first auto-trade strategy. ₹20K minimum.",
        "category": "equity_swing",
        "segment": "EQUITY",
        "tier_required": "free",
        "min_capital": 20_000,
        "risk_level": "low",
        "tags": ["beginner", "starter", "micro-capital", "trend-following", "ema"],
        "is_featured": True,
        "engine_compatible": False,
        "dsl": {
            "name": "Starter — Single-EMA Trend Follow",
            "universe": "nifty50",
            "timeframe": "1d",
            "entry": {
                "kind": "composite_and",
                "children": [
                    {"kind": "indicator_cross",   "indicator": "close", "op": "crosses_above", "value": "ema21"},
                    {"kind": "indicator_compare", "indicator": "adx",   "op": ">", "value": 20},
                ],
            },
            "exit": {"kind": "indicator_compare", "indicator": "close", "op": "<", "value": "ema21"},
            "stop_loss_pct": 3,
            "take_profit_pct": 8,
            "position_size": {"kind": "percent_of_capital", "value": 30},
            "lookback_days": 180,
            "mode": "backtest",
        },
    },
    # ────────────────────────────────────────────────────────────
    # PR-L FinStocks /strategy-templates (authenticated page)
    # Pasted by user from their dashboard. NIFTY100 swing templates.
    # Notes on adaptations:
    #   - prior-bar refs (prev_macd_hist, prev_atr14) dropped — not in DSL
    #   - DIplus/DIminus dropped — we use ADX-only
    #   - stoch_rsi_k approximated by stochastic_k (~80% correlated)
    #   - sma9 substituted with sma10 (nearest in our SMA family)
    #   - brokerage-floor (entry*1.004) dropped — already in our cost model
    #     (slippage 0.05% + brokerage 0.03% + STT 0.10% per side)
    #   - hard SL 7% / TP 10% kept verbatim per FinStocks spec
    # ────────────────────────────────────────────────────────────
    {
        "slug": "macd-bull-cross-uptrend-swing",
        "name": "MACD Bull Cross + Uptrend Swing",
        "description": "MACD crosses above signal with positive histogram, inside a 50/200-EMA uptrend with ADX>20. NIFTY100 swing.",
        "category": "equity_swing",
        "segment": "EQUITY",
        "tier_required": "pro",
        "min_capital": 100_000,
        "risk_level": "medium",
        "tags": ["finstocks-inspired", "macd", "swing", "trend-following"],
        "is_featured": False,
        "engine_compatible": False,
        "dsl": {
            "name": "MACD Bull Cross + Uptrend Swing",
            "universe": "nifty100",
            "timeframe": "1d",
            "entry": {
                "kind": "composite_and",
                "children": [
                    {"kind": "indicator_cross",   "indicator": "macd",      "op": "crosses_above", "value": "macd_signal"},
                    {"kind": "indicator_compare", "indicator": "macd_hist", "op": ">",  "value": 0},
                    {"kind": "indicator_compare", "indicator": "ema50",     "op": ">",  "value": "ema200"},
                    {"kind": "indicator_compare", "indicator": "adx",       "op": ">",  "value": 20},
                    {"kind": "indicator_compare", "indicator": "rsi14",     "op": ">=", "value": 45},
                ],
            },
            "exit": {"kind": "indicator_cross", "indicator": "macd", "op": "crosses_below", "value": "macd_signal"},
            "stop_loss_pct": 7,
            "take_profit_pct": 10,
            "position_size": {"kind": "percent_of_capital", "value": 10},
            "lookback_days": 180,
            "mode": "backtest",
        },
    },
    {
        "slug": "macd-histogram-rising-uptrend-swing",
        "name": "MACD Histogram Rising + Uptrend Swing",
        "description": "MACD histogram positive (rising momentum proxy) inside a 50/200-EMA uptrend with ADX>22. NIFTY100 swing.",
        "category": "equity_swing",
        "segment": "EQUITY",
        "tier_required": "pro",
        "min_capital": 100_000,
        "risk_level": "medium",
        "tags": ["finstocks-inspired", "macd", "histogram", "swing"],
        "is_featured": False,
        "engine_compatible": False,
        "is_exclusive": True,
        "exclusive_tagline": "Histogram-driven momentum with trend confirmation",
        "dsl": {
            "name": "MACD Histogram Rising + Uptrend Swing",
            "universe": "nifty100",
            "timeframe": "1d",
            "entry": {
                "kind": "composite_and",
                "children": [
                    {"kind": "indicator_compare", "indicator": "macd_hist", "op": ">",  "value": 0},
                    {"kind": "indicator_compare", "indicator": "ema50",     "op": ">",  "value": "ema200"},
                    {"kind": "indicator_compare", "indicator": "adx",       "op": ">",  "value": 22},
                    {"kind": "indicator_compare", "indicator": "rsi14",     "op": ">=", "value": 45},
                ],
            },
            "exit": {"kind": "indicator_compare", "indicator": "macd_hist", "op": "<", "value": 0},
            "stop_loss_pct": 7,
            "take_profit_pct": 10,
            "position_size": {"kind": "percent_of_capital", "value": 10},
            "lookback_days": 180,
            "mode": "backtest",
        },
    },
    {
        "slug": "mfi-healthy-uptrend-swing",
        "name": "MFI Healthy + Uptrend Swing",
        "description": "Money Flow Index in the healthy 40-60 zone inside a 50/200-EMA uptrend, close > EMA50, ADX>20. NIFTY100 swing.",
        "category": "equity_swing",
        "segment": "EQUITY",
        "tier_required": "pro",
        "min_capital": 100_000,
        "risk_level": "medium",
        "tags": ["finstocks-inspired", "mfi", "swing", "trend-following"],
        "is_featured": False,
        "engine_compatible": False,
        "is_exclusive": True,
        "exclusive_tagline": "Five-filter trend swing with volume-aware entry",
        "dsl": {
            "name": "MFI Healthy + Uptrend Swing",
            "universe": "nifty100",
            "timeframe": "1d",
            "entry": {
                "kind": "composite_and",
                "children": [
                    {"kind": "indicator_compare", "indicator": "mfi",   "op": "between", "value": [40, 60]},
                    {"kind": "indicator_compare", "indicator": "ema50", "op": ">",       "value": "ema200"},
                    {"kind": "indicator_compare", "indicator": "close", "op": ">",       "value": "ema50"},
                    {"kind": "indicator_compare", "indicator": "adx",   "op": ">",       "value": 20},
                    {"kind": "indicator_compare", "indicator": "rsi14", "op": ">=",      "value": 48},
                ],
            },
            "exit": {"kind": "indicator_compare", "indicator": "mfi", "op": ">", "value": 75},
            "stop_loss_pct": 7,
            "take_profit_pct": 10,
            "position_size": {"kind": "percent_of_capital", "value": 10},
            "lookback_days": 180,
            "mode": "backtest",
        },
    },
    {
        "slug": "atr-expansion-uptrend-swing",
        "name": "ATR Expansion + Uptrend Swing",
        "description": "Close > EMA21 inside a 50/200-EMA uptrend with ADX>22 and RSI healthy. NIFTY100 swing.",
        "category": "equity_swing",
        "segment": "EQUITY",
        "tier_required": "pro",
        "min_capital": 100_000,
        "risk_level": "medium",
        "tags": ["finstocks-inspired", "atr", "swing", "trend-following"],
        "is_featured": False,
        "engine_compatible": False,
        "is_exclusive": True,
        "exclusive_tagline": "Volatility-confirmed trend swing with RSI sweet spot",
        "dsl": {
            "name": "ATR Expansion + Uptrend Swing",
            "universe": "nifty100",
            "timeframe": "1d",
            "entry": {
                "kind": "composite_and",
                "children": [
                    {"kind": "indicator_compare", "indicator": "close", "op": ">",       "value": "ema21"},
                    {"kind": "indicator_compare", "indicator": "ema50", "op": ">",       "value": "ema200"},
                    {"kind": "indicator_compare", "indicator": "adx",   "op": ">",       "value": 22},
                    {"kind": "indicator_compare", "indicator": "rsi14", "op": "between", "value": [45, 65]},
                ],
            },
            "exit": {"kind": "indicator_compare", "indicator": "close", "op": "<", "value": "ema21"},
            "stop_loss_pct": 7,
            "take_profit_pct": 10,
            "position_size": {"kind": "percent_of_capital", "value": 10},
            "lookback_days": 180,
            "mode": "backtest",
        },
    },
    {
        "slug": "stochrsi-oversold-ema-uptrend",
        "name": "StochRSI Oversold + EMA Uptrend",
        "description": "Stochastic oversold (Stoch K < 20) inside a triple-EMA uptrend (EMA8 > EMA21 > EMA50). NIFTY100 swing.",
        "category": "equity_swing",
        "segment": "EQUITY",
        "tier_required": "pro",
        "min_capital": 100_000,
        "risk_level": "medium",
        "tags": ["finstocks-inspired", "stochastic", "swing", "pullback"],
        "is_featured": False,
        "engine_compatible": False,
        "dsl": {
            "name": "StochRSI Oversold + EMA Uptrend",
            "universe": "nifty100",
            "timeframe": "1d",
            "entry": {
                "kind": "composite_and",
                "children": [
                    {"kind": "indicator_compare", "indicator": "stochastic_k", "op": "<", "value": 20},
                    {"kind": "indicator_compare", "indicator": "ema8",         "op": ">", "value": "ema21"},
                    {"kind": "indicator_compare", "indicator": "ema21",        "op": ">", "value": "ema50"},
                    {"kind": "indicator_compare", "indicator": "close",        "op": ">", "value": "ema50"},
                ],
            },
            "exit": {"kind": "indicator_compare", "indicator": "stochastic_k", "op": ">", "value": 75},
            "stop_loss_pct": 7,
            "take_profit_pct": 10,
            "position_size": {"kind": "percent_of_capital", "value": 10},
            "lookback_days": 180,
            "mode": "backtest",
        },
    },
    {
        "slug": "sma-cross-uptrend-swing",
        "name": "SMA Cross + Uptrend Swing",
        "description": "Fast SMA10 > SMA50 cross inside a 50/200-EMA uptrend with ADX>22. NIFTY100 swing.",
        "category": "equity_swing",
        "segment": "EQUITY",
        "tier_required": "free",
        "min_capital": 50_000,
        "risk_level": "low",
        "tags": ["finstocks-inspired", "sma", "swing", "crossover", "beginner"],
        "is_featured": False,
        "engine_compatible": False,
        "dsl": {
            "name": "SMA Cross + Uptrend Swing",
            "universe": "nifty100",
            "timeframe": "1d",
            "entry": {
                "kind": "composite_and",
                "children": [
                    {"kind": "indicator_compare", "indicator": "sma10", "op": ">",  "value": "sma50"},
                    {"kind": "indicator_compare", "indicator": "close", "op": ">",  "value": "sma10"},
                    {"kind": "indicator_compare", "indicator": "ema50", "op": ">",  "value": "ema200"},
                    {"kind": "indicator_compare", "indicator": "adx",   "op": ">",  "value": 22},
                    {"kind": "indicator_compare", "indicator": "rsi14", "op": ">=", "value": 45},
                ],
            },
            "exit": {"kind": "indicator_compare", "indicator": "close", "op": "<", "value": "sma10"},
            "stop_loss_pct": 7,
            "take_profit_pct": 10,
            "position_size": {"kind": "percent_of_capital", "value": 10},
            "lookback_days": 180,
            "mode": "backtest",
        },
    },
    {
        "slug": "adx-trend-ema-psar",
        "name": "ADX Trend + EMA50/200 + Parabolic SAR",
        "description": "Long when ADX>22, 50/200-EMA bull stack, AND close > Parabolic SAR. Trailing exit when SAR flips. NIFTY100 swing.",
        "category": "equity_swing",
        "segment": "EQUITY",
        "tier_required": "pro",
        "min_capital": 100_000,
        "risk_level": "medium",
        "tags": ["finstocks-inspired", "adx", "psar", "swing", "trend-following"],
        "is_featured": False,
        "engine_compatible": False,
        "dsl": {
            "name": "ADX Trend + EMA50/200 + Parabolic SAR",
            "universe": "nifty100",
            "timeframe": "1d",
            "entry": {
                "kind": "composite_and",
                "children": [
                    {"kind": "indicator_compare", "indicator": "adx",   "op": ">", "value": 22},
                    {"kind": "indicator_compare", "indicator": "ema50", "op": ">", "value": "ema200"},
                    {"kind": "indicator_compare", "indicator": "close", "op": ">", "value": "psar"},
                ],
            },
            "exit": {"kind": "indicator_compare", "indicator": "close", "op": "<", "value": "psar"},
            "stop_loss_pct": 7,
            "take_profit_pct": 10,
            "position_size": {"kind": "percent_of_capital", "value": 10},
            "lookback_days": 180,
            "mode": "backtest",
        },
    },
    {
        "slug": "stochastic-oversold-pullback-uptrend",
        "name": "Stochastic Oversold Pullback in Uptrend",
        "description": "Buy Stochastic K<25 with K>D crossover inside a 50/200-EMA uptrend, close > EMA50. NIFTY100 swing.",
        "category": "equity_swing",
        "segment": "EQUITY",
        "tier_required": "pro",
        "min_capital": 100_000,
        "risk_level": "medium",
        "tags": ["finstocks-inspired", "stochastic", "pullback", "swing"],
        "is_featured": False,
        "engine_compatible": False,
        "dsl": {
            "name": "Stochastic Oversold Pullback in Uptrend",
            "universe": "nifty100",
            "timeframe": "1d",
            "entry": {
                "kind": "composite_and",
                "children": [
                    {"kind": "indicator_compare", "indicator": "stochastic_k", "op": "<", "value": 25},
                    {"kind": "indicator_compare", "indicator": "stochastic_k", "op": ">", "value": "stochastic_d"},
                    {"kind": "indicator_compare", "indicator": "ema50",        "op": ">", "value": "ema200"},
                    {"kind": "indicator_compare", "indicator": "close",        "op": ">", "value": "ema50"},
                ],
            },
            "exit": {"kind": "indicator_compare", "indicator": "stochastic_k", "op": ">", "value": 75},
            "stop_loss_pct": 7,
            "take_profit_pct": 10,
            "position_size": {"kind": "percent_of_capital", "value": 10},
            "lookback_days": 180,
            "mode": "backtest",
        },
    },
    {
        "slug": "pivot-point-support-rsi",
        "name": "Pivot Point Support + RSI",
        "description": "Buy a bounce off the classic pivot S1 while still below the pivot, with RSI>42 and a 50/200-EMA uptrend. Targets pivot R1.",
        "category": "equity_swing",
        "segment": "EQUITY",
        "tier_required": "pro",
        "min_capital": 100_000,
        "risk_level": "medium",
        "tags": ["pivot-points", "swing", "support-resistance", "mean-reversion"],
        "engine_compatible": False,
        "dsl": {
            "name": "Pivot Point Support + RSI",
            "universe": "nifty100",
            "timeframe": "1d",
            "entry": {
                "kind": "composite_and",
                "children": [
                    {"kind": "indicator_compare", "indicator": "ema50", "op": ">", "value": "ema200"},
                    {"kind": "indicator_compare", "indicator": "close", "op": ">", "value": "pivot_s1"},
                    {"kind": "indicator_compare", "indicator": "close", "op": "<", "value": "pivot_point"},
                    {"kind": "indicator_compare", "indicator": "rsi14", "op": ">", "value": 42},
                ],
            },
            "exit": {
                "kind": "composite_or",
                "children": [
                    {"kind": "indicator_compare", "indicator": "close", "op": ">", "value": "pivot_r1"},
                    {"kind": "indicator_compare", "indicator": "close", "op": "<", "value": "pivot_s1"},
                    {"kind": "indicator_compare", "indicator": "rsi14", "op": ">", "value": 70},
                ],
            },
            "stop_loss_pct": 3,
            "take_profit_pct": 6,
            "position_size": {"kind": "percent_of_capital", "value": 5},
            "regime_filter": "bull_only",
            "lookback_days": 180,
            "mode": "backtest",
        },
    },
    {
        "slug": "donchian-breakout-trend",
        "name": "Donchian Breakout (Turtle)",
        "description": "Classic turtle breakout: buy a close above the 20-day Donchian high in a confirmed uptrend; exit on a 20-day low break or EMA50 loss.",
        "category": "equity_swing",
        "segment": "EQUITY",
        "tier_required": "free",
        "min_capital": 50_000,
        "risk_level": "medium",
        "tags": ["trend", "breakout", "donchian", "turtle"],
        "engine_compatible": False,
        "dsl": {
            "name": "Donchian Breakout (Turtle)",
            "universe": "nifty100",
            "timeframe": "1d",
            "entry": {
                "kind": "composite_and",
                "children": [
                    {"kind": "indicator_compare", "indicator": "close", "op": ">", "value": "donchian_high_20"},
                    {"kind": "indicator_compare", "indicator": "close", "op": ">", "value": "ema50"},
                ],
            },
            "exit": {
                "kind": "composite_or",
                "children": [
                    {"kind": "indicator_compare", "indicator": "close", "op": "<", "value": "donchian_low_20"},
                    {"kind": "indicator_compare", "indicator": "close", "op": "<", "value": "ema50"},
                ],
            },
            "stop_loss_pct": 5,
            "take_profit_pct": 12,
            "position_size": {"kind": "percent_of_capital", "value": 5},
            "regime_filter": "bull_only",
            "lookback_days": 250,
            "mode": "backtest",
        },
    },
]


# ─────────────────────────────────────────────────────────────────────
# Metadata-only stubs for FinStocks templates we can't DSL yet.
# These appear in the catalog (visible / discoverable) but `from-template`
# returns 409 with the documented reason — drives the "Coming soon"
# state on the discovery page.
# ─────────────────────────────────────────────────────────────────────
COMING_SOON: List[Dict[str, Any]] = [
    {
        "slug": "low-pe-value-investing",
        "name": "Low P/E Value Investing",
        "description": "Instantly buy stocks with low P/E ratio and sell at 5% profit. Coming soon — requires fundamental data ingestion.",
        "category": "equity_investing",
        "segment": "EQUITY",
        "tier_required": "pro",
        "min_capital": 100_000,
        "risk_level": "low",
        "tags": ["finstocks-inspired", "fundamental", "value", "coming-soon"],
        "blocked_reason": "fundamentals_not_yet_indexed",
        "blocked_eta": "v1.1 — fundamentals ingestion (P/E, P/B, ROE) lands with quarterly screener refresh",
    },
    {
        "slug": "high-roi-momentum",
        "name": "High ROI Momentum",
        "description": "Buy stocks with high ROI and sell at 5% profit. Coming soon — requires fundamental data ingestion.",
        "category": "equity_investing",
        "segment": "EQUITY",
        "tier_required": "pro",
        "min_capital": 100_000,
        "risk_level": "medium",
        "tags": ["finstocks-inspired", "fundamental", "momentum", "coming-soon"],
        "blocked_reason": "fundamentals_not_yet_indexed",
        "blocked_eta": "v1.1 — fundamentals ingestion lands with quarterly screener refresh",
    },
    {
        "slug": "high-promoter-holding",
        "name": "High Promoter Holding",
        "description": "Buy Nifty 100 stocks with promoter shareholding > 50% and sell at 5% profit. Coming soon — requires shareholding ingestion.",
        "category": "equity_investing",
        "segment": "EQUITY",
        "tier_required": "free",
        "min_capital": 50_000,
        "risk_level": "low",
        "tags": ["finstocks-inspired", "fundamental", "promoter-holding", "coming-soon"],
        "blocked_reason": "shareholding_data_not_yet_indexed",
        "blocked_eta": "v1.1 — quarterly shareholding scrape from BSE/NSE filings",
    },
    {
        "slug": "open-range-breakout",
        "name": "Open Range Breakout",
        "description": "5-minute opening range breakout for NSE equities with gap + volume + 52w-high filters. Coming soon — needs intraday session indicators.",
        "category": "equity_intraday",
        "segment": "EQUITY",
        "tier_required": "pro",
        "min_capital": 100_000,
        "risk_level": "high",
        "tags": ["finstocks-inspired", "intraday", "orb", "breakout", "coming-soon"],
        "blocked_reason": "intraday_session_indicators_not_yet_supported",
        "blocked_eta": "v1.2 — adds bar_of_day, opening_range_high/low, gap_pct, dist_from_52w_high to INDICATOR_REGISTRY",
    },
]


def seed():
    sb = get_supabase_admin()
    inserted = 0
    updated = 0
    rejected = 0

    for tpl in TEMPLATES:
        slug = tpl["slug"]
        # Validate DSL Pydantic-side before sending to DB
        try:
            Strategy.model_validate(tpl["dsl"])
        except Exception as exc:
            logger.error("REJECTED %s: DSL validation failed: %s", slug, exc)
            rejected += 1
            continue

        payload = {
            "slug": slug,
            "name": tpl["name"],
            "description": tpl["description"],
            "category": tpl["category"],
            "segment": tpl["segment"],
            "template_slug": tpl.get("template_slug", tpl["category"]),
            "strategy_class": tpl.get("strategy_class", "dsl.runtime"),
            "tier_required": tpl["tier_required"],
            "min_capital": tpl["min_capital"],
            "risk_level": tpl["risk_level"],
            "tags": tpl.get("tags", []),
            "requires_fo_enabled": tpl["segment"] != "EQUITY",
            "is_featured": tpl.get("is_featured", False),
            "is_active": True,
            "engine_compatible": tpl["engine_compatible"],
            "dsl": tpl["dsl"],
            "is_exclusive": tpl.get("is_exclusive", False),
            "exclusive_tagline": tpl.get("exclusive_tagline"),
        }

        # Try update first; fall back to insert
        existing = sb.table("strategy_catalog").select("id").eq("slug", slug).limit(1).execute()
        if existing.data:
            sb.table("strategy_catalog").update(payload).eq("slug", slug).execute()
            updated += 1
            logger.info("  UPDATED %s", slug)
        else:
            sb.table("strategy_catalog").insert(payload).execute()
            inserted += 1
            logger.info("  INSERTED %s", slug)

    logger.info("Done: %d inserted, %d updated, %d rejected (%d templates total)",
                inserted, updated, rejected, len(TEMPLATES))

    # ── Coming-soon stubs (metadata only, dsl=NULL) ────────────────
    cs_inserted = 0
    cs_updated = 0
    for tpl in COMING_SOON:
        slug = tpl["slug"]
        # Stash the blocked-reason + ETA in tags so the frontend can render
        # a "Coming soon" badge without us adding new columns.
        tags = list(tpl.get("tags", [])) + [
            f"blocked:{tpl['blocked_reason']}",
        ]
        payload = {
            "slug": slug,
            "name": tpl["name"],
            "description": tpl["description"] + " ETA: " + tpl["blocked_eta"],
            "category": tpl["category"],
            "segment": tpl["segment"],
            "template_slug": tpl["category"],
            "strategy_class": "dsl.runtime",
            "tier_required": tpl["tier_required"],
            "min_capital": tpl["min_capital"],
            "risk_level": tpl["risk_level"],
            "tags": tags,
            "requires_fo_enabled": False,
            "is_featured": False,
            "is_active": True,
            "engine_compatible": False,
            "dsl": None,            # explicit — drives the 409 in /from-template
            "is_exclusive": False,
        }
        existing = sb.table("strategy_catalog").select("id").eq("slug", slug).limit(1).execute()
        if existing.data:
            sb.table("strategy_catalog").update(payload).eq("slug", slug).execute()
            cs_updated += 1
            logger.info("  UPDATED (coming-soon) %s", slug)
        else:
            sb.table("strategy_catalog").insert(payload).execute()
            cs_inserted += 1
            logger.info("  INSERTED (coming-soon) %s", slug)
    logger.info("Coming-soon: %d inserted, %d updated (%d total)",
                cs_inserted, cs_updated, len(COMING_SOON))


if __name__ == "__main__":
    seed()
