-- PR-G1 — Strategy Discovery Engine: schema
--
-- Adds two tables:
--   strategy_search_runs    — one row per discovery batch (cron or ad-hoc)
--   discovered_strategies   — per-candidate (rule + backtest stats + score)
--
-- A "run" samples N candidates from a search space (equity_swing,
-- equity_position, fo_weekly, fo_monthly), backtests each on rolling
-- windows, scores them, and persists everything. The user reviews
-- top-K via the Discovered tab and promotes winners to user_strategies.
--
-- LOCKED: candidates are generated by deterministic search over the
-- DSL parameter space (genetic / random / Sobol). NEVER by an LLM —
-- see project_agents_decision_2026_05_10.md.

-- ─── strategy_search_runs ──────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS strategy_search_runs (
  id              UUID PRIMARY KEY DEFAULT gen_random_uuid(),

  -- Search domain. One run targets exactly one of these spaces.
  -- equity_swing    — daily-bar single-instrument or universe, 5-20 day hold
  -- equity_position — daily-bar, 20-90 day hold, fundamentals tilt
  -- fo_weekly       — weekly NSE options, current/next week expiry
  -- fo_monthly      — monthly NSE options, current/next month expiry
  kind            TEXT NOT NULL CHECK (kind IN (
    'equity_swing', 'equity_position', 'fo_weekly', 'fo_monthly'
  )),

  -- Config snapshot — search space definition, sample size, time window,
  -- universe, scoring function. Frozen at run-start so re-runs are
  -- reproducible.
  config          JSONB NOT NULL,

  status          TEXT NOT NULL DEFAULT 'pending'
                  CHECK (status IN ('pending','running','completed','failed','cancelled')),
  error           TEXT,

  -- Lifecycle
  started_at      TIMESTAMPTZ,
  completed_at    TIMESTAMPTZ,
  created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),

  -- Aggregates filled in at completion — saves a JOIN on the list view.
  candidates_total      INTEGER DEFAULT 0,
  candidates_viable     INTEGER DEFAULT 0,   -- passed min_trades + min_sharpe filter
  best_score            NUMERIC(12, 6),
  best_candidate_id     UUID,

  -- Who triggered: null = system cron, non-null = user request.
  triggered_by_user_id  UUID,

  metadata        JSONB DEFAULT '{}'::jsonb
);

CREATE INDEX IF NOT EXISTS idx_strategy_search_runs_kind_started
  ON strategy_search_runs(kind, started_at DESC);
CREATE INDEX IF NOT EXISTS idx_strategy_search_runs_status
  ON strategy_search_runs(status)
  WHERE status IN ('pending', 'running');


-- ─── discovered_strategies ─────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS discovered_strategies (
  id              UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  run_id          UUID NOT NULL
                  REFERENCES strategy_search_runs(id) ON DELETE CASCADE,

  -- Auto-generated human-readable label. Composed by the runner from the
  -- candidate's key knobs (e.g. "RSI(14)<30 + Mood>0.2 [bull-only]").
  label           TEXT NOT NULL,

  -- Same kind as the parent run — duplicated for fast filtering.
  kind            TEXT NOT NULL CHECK (kind IN (
    'equity_swing', 'equity_position', 'fo_weekly', 'fo_monthly'
  )),

  -- The full Strategy DSL document the user would promote. Validated
  -- through backend.ai.strategy.dsl.Strategy.model_validate at insert
  -- time (via the API layer), so we never persist a broken DSL.
  dsl             JSONB NOT NULL,

  -- ─── Scoring ────────────────────────────────────────────────────────
  -- Primary composite score used for the leaderboard. Higher = better.
  -- Formula lives in the evaluator; usually a blend of net Sharpe,
  -- profit factor, and a stability penalty across regimes.
  score           NUMERIC(12, 6) NOT NULL,

  -- Decomposition — same fields exposed in the UI so the user can sort
  -- by what they care about.
  sharpe          NUMERIC(10, 4),
  calmar          NUMERIC(10, 4),
  max_drawdown_pct NUMERIC(10, 4),
  win_rate        NUMERIC(6, 4),
  profit_factor   NUMERIC(10, 4),
  total_return_pct NUMERIC(12, 4),
  trade_count     INTEGER,
  avg_hold_days   NUMERIC(8, 2),

  -- Per-regime scoring breakdown ({bull: 1.8, sideways: 0.4, bear: -0.2}).
  -- Used by the stability filter — a strategy that only works in one
  -- regime is risky; we surface that in the UI as a "regime concentration"
  -- warning.
  regime_scores   JSONB DEFAULT '{}'::jsonb,

  -- Walk-forward window stats: list of per-fold scores so the user can
  -- see if the strategy decayed (e.g. 2.1 → 1.7 → 0.4 → -0.1) or was
  -- consistent. Empty when single-window backtest.
  walk_forward    JSONB DEFAULT '[]'::jsonb,

  -- Lineage — when the GA mutates a parent into a child, we record it
  -- for inspection ("this strategy descends from candidate X with mutated
  -- RSI threshold").
  parent_id       UUID REFERENCES discovered_strategies(id) ON DELETE SET NULL,
  generation      INTEGER DEFAULT 0,

  -- Lifecycle: candidate → promoted (user pushed to user_strategies) →
  -- archived (user dismissed) → failed (eval errored).
  status          TEXT NOT NULL DEFAULT 'candidate'
                  CHECK (status IN ('candidate','promoted','archived','failed')),
  promoted_to_strategy_id UUID,   -- FK-like: user_strategies.id
  promoted_at     TIMESTAMPTZ,
  promoted_by_user_id     UUID,

  created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Leaderboard query: by run, by score DESC.
CREATE INDEX IF NOT EXISTS idx_discovered_strategies_run_score
  ON discovered_strategies(run_id, score DESC);

-- Cross-run leaderboard for a kind: "top swing strategies discovered ever".
CREATE INDEX IF NOT EXISTS idx_discovered_strategies_kind_score
  ON discovered_strategies(kind, score DESC)
  WHERE status = 'candidate';

-- For the promotion review UI ("my promoted strategies").
CREATE INDEX IF NOT EXISTS idx_discovered_strategies_promoted
  ON discovered_strategies(promoted_by_user_id, promoted_at DESC)
  WHERE status = 'promoted';
