"""Discovery runner — orchestrates a full search batch end-to-end.

A run takes a (kind, mode, config) tuple, samples or evolves N candidates
from the search space, evaluates each against the universe, optionally
computes walk-forward folds, persists results to Supabase, and updates
the parent run row with aggregates.

Two search modes:
  * `random` — N random draws from the search space (fast, broad)
  * `ga`     — multi-generation elitist GA (slower, focused)

Walk-forward: when `walk_forward_folds > 1`, every candidate that
qualifies (enough bars, >0 trades on the full window) gets a per-fold
breakdown persisted into `walk_forward` JSONB. A stability penalty
based on fold-to-fold Sharpe variance is folded into the composite
score so a strategy that "decays from 2.0 → -0.5" gets ranked below
one with a flat 0.9 across all folds.

Concurrency: candidates are evaluated sequentially per-symbol but
multiple symbols are processed in a thread pool (with per-symbol bars
cached up front).

LOCKED: candidates are generated by deterministic search over the DSL
parameter space — never by an LLM. See
``project_agents_decision_2026_05_10`` memory entry.
"""

from __future__ import annotations

import logging
import statistics
import time
from concurrent.futures import ThreadPoolExecutor, as_completed
from dataclasses import asdict, dataclass, field
from datetime import datetime, timezone
from typing import Any, Dict, List, Optional, Tuple
from uuid import UUID

from backend.ai.qlib.data_handler import load_universe
from backend.ai.strategy.dsl import Strategy
from backend.ai.strategy_discovery.evaluator import (
    CandidateScore,
    evaluate_candidate,
)
from backend.ai.strategy_discovery.genetic import GAConfig, evolve
from backend.ai.strategy_discovery.intraday_space import IntradaySearchSpace
from backend.ai.strategy_discovery.search_space import (
    EquitySearchSpace,
    FOSearchSpace,
)
from backend.ai.strategy_discovery.walk_forward import (
    score_walk_forward,
    stability_score,
)
from backend.core.database import get_supabase_admin
from backend.data.market import get_market_data_provider

logger = logging.getLogger(__name__)


# ─────────────────────────────────────────────────────────────────────
# Config
# ─────────────────────────────────────────────────────────────────────


@dataclass
class DiscoveryConfig:
    """Inputs that fully determine what a run does.

    Persisted verbatim in `strategy_search_runs.config` so the run is
    reproducible — re-run with the same config + seed and you get the
    same ranking.
    """
    kind: str                            # equity_swing | equity_position | fo_weekly | fo_monthly
    mode: str = "random"                 # "random" | "ga"
    sample_size: int = 30                # candidates (random mode only)
    universe: str = "nifty50"            # equity tier or F&O underlying
    symbols_per_candidate: int = 8       # symbols to evaluate against
    history_period: str = "2y"           # daily-bar history per symbol
    initial_capital: float = 100_000.0
    seed: int = 42
    max_workers: int = 4                 # concurrent symbol fetches

    # ── GA-mode knobs (ignored when mode='random') ────────────────────
    ga_pop_size: int = 12
    ga_generations: int = 3
    ga_elite: int = 4
    ga_children_per_elite: int = 2

    # ── Walk-forward knobs ────────────────────────────────────────────
    # 0 or 1 = no walk-forward (just blended single-window stats).
    # 3 = standard 3-fold; needs >= 240 bars per symbol.
    walk_forward_folds: int = 0

    def to_dict(self) -> Dict[str, Any]:
        return asdict(self)


@dataclass
class AggregateScore:
    """A candidate's score collapsed across all symbols in the universe."""
    candidate_idx: int
    strategy: Strategy
    per_symbol: List[CandidateScore]
    mean_score: float
    mean_sharpe: float
    mean_drawdown: float
    mean_win_rate: float
    total_trades: int
    viable_symbols: int
    walk_forward: List[Dict[str, Any]] = field(default_factory=list)
    stability: float = 0.0
    generation: int = 0
    parent_label: Optional[str] = None

    def to_row(self, run_id: UUID, kind: str) -> Dict[str, Any]:
        """Build the `discovered_strategies` insert payload."""
        top_symbol = max(self.per_symbol, key=lambda s: s.score) if self.per_symbol else None
        regime = _aggregate_regimes(self.per_symbol)
        return {
            "run_id": str(run_id),
            "label": _aggregate_label(
                self.strategy, self.mean_sharpe, self.viable_symbols,
                self.generation, self.parent_label,
            ),
            "kind": kind,
            "dsl": self.strategy.model_dump(mode="json"),
            "score": round(self.mean_score, 6),
            "sharpe": round(self.mean_sharpe, 4),
            "calmar": round(top_symbol.calmar, 4) if top_symbol else 0.0,
            "max_drawdown_pct": round(self.mean_drawdown, 4),
            "win_rate": round(self.mean_win_rate, 4),
            "profit_factor": round(top_symbol.profit_factor, 4) if top_symbol else 0.0,
            "total_return_pct": round(top_symbol.total_return_pct, 4) if top_symbol else 0.0,
            "trade_count": self.total_trades,
            "avg_hold_days": round(top_symbol.avg_hold_days, 2) if top_symbol else 0.0,
            "regime_scores": regime,
            "walk_forward": self.walk_forward,
            "generation": self.generation,
            "status": "candidate",
        }


def _aggregate_label(
    strategy: Strategy, mean_sharpe: float, viable: int,
    generation: int = 0, parent_label: Optional[str] = None,
) -> str:
    seg = strategy.instrument_segment.value.lower()
    gen_part = f" · gen{generation}" + (f" ←{parent_label}" if parent_label else "")
    if seg == "options":
        legs = len(strategy.legs or [])
        return (
            f"{strategy.name} · {legs}-leg · meanSharpe {mean_sharpe:.2f} · "
            f"viable on {viable} symbols{gen_part}"
        )
    return (
        f"{strategy.name} · {strategy.timeframe.value} · "
        f"meanSharpe {mean_sharpe:.2f} · viable on {viable} symbols{gen_part}"
    )


def _aggregate_regimes(per_symbol: List[CandidateScore]) -> Dict[str, Any]:
    """Average per-regime scores across symbols."""
    bull, sideways, bear = [], [], []
    bull_n, side_n, bear_n = 0, 0, 0
    for cs in per_symbol:
        rb = cs.regime_breakdown
        if rb.bull_trades > 0:
            bull.append(rb.bull)
            bull_n += rb.bull_trades
        if rb.sideways_trades > 0:
            sideways.append(rb.sideways)
            side_n += rb.sideways_trades
        if rb.bear_trades > 0:
            bear.append(rb.bear)
            bear_n += rb.bear_trades
    return {
        "bull": round(statistics.mean(bull), 4) if bull else 0.0,
        "sideways": round(statistics.mean(sideways), 4) if sideways else 0.0,
        "bear": round(statistics.mean(bear), 4) if bear else 0.0,
        "bull_trades": bull_n,
        "sideways_trades": side_n,
        "bear_trades": bear_n,
    }


# ─────────────────────────────────────────────────────────────────────
# Universe + data fetch
# ─────────────────────────────────────────────────────────────────────


def _resolve_symbols(cfg: DiscoveryConfig) -> List[str]:
    """Pick the symbols a run will evaluate against."""
    import random
    rng = random.Random(cfg.seed)

    if cfg.kind.startswith("fo_"):
        return [
            cfg.universe.upper()
            if cfg.universe.upper() in ("NIFTY", "BANKNIFTY", "FINNIFTY")
            else "NIFTY"
        ]

    pool = load_universe(cfg.universe)
    if not pool:
        pool = ["RELIANCE", "TCS", "INFY", "HDFCBANK", "ICICIBANK"]
    n = min(cfg.symbols_per_candidate, len(pool))
    return rng.sample(pool, n)


def _fetch_bars_cached(symbol: str, period: str = "2y", interval: str = "1d"):
    """Pull OHLCV via the shared provider. Returns lowercase-column df.

    For intraday intervals (5m, 15m, etc.) yfinance limits look-back to
    ~60 days, so callers should pass a short `period` like '30d' or '60d'.
    Kite serves much longer windows but is slower.
    """
    mp = get_market_data_provider()
    try:
        bars = mp.get_historical(symbol, period=period, interval=interval)
    except Exception as e:
        logger.warning("data fetch failed for %s [%s]: %s", symbol, interval, e)
        return None
    if bars is None or bars.empty:
        return None
    bars = bars.copy()
    bars.columns = [c.lower() for c in bars.columns]
    return bars


def _kind_interval(kind: str) -> str:
    """Daily vs intraday bar interval for a discovery kind."""
    if kind == "intraday_5m":
        return "5m"
    if kind == "intraday_15m":
        return "15m"
    return "1d"


def _kind_default_period(kind: str, requested: str) -> str:
    """Cap the history period to what the data provider can serve.

    yfinance limits intraday windows: 1m=~7 days, 5m/15m=~60 days.
    Kite gives more but defaults match yfinance to keep the runner
    compatible across DATA_PROVIDER=free/kite.
    """
    if kind == "intraday_5m" and requested in ("2y", "3y", "5y", "max"):
        return "60d"
    if kind == "intraday_15m" and requested in ("2y", "3y", "5y", "max"):
        return "60d"
    return requested


# ─────────────────────────────────────────────────────────────────────
# Search-space factory
# ─────────────────────────────────────────────────────────────────────


def _build_space(cfg: DiscoveryConfig):
    """Translate cfg.kind into the concrete sampler object."""
    if cfg.kind == "equity_swing":
        return EquitySearchSpace(horizon="swing", seed=cfg.seed)
    if cfg.kind == "equity_position":
        return EquitySearchSpace(horizon="position", seed=cfg.seed)
    if cfg.kind == "fo_weekly":
        return FOSearchSpace(tenor="weekly", underlying=cfg.universe.upper(), seed=cfg.seed)
    if cfg.kind == "fo_monthly":
        return FOSearchSpace(tenor="monthly", underlying=cfg.universe.upper(), seed=cfg.seed)
    if cfg.kind == "intraday_5m":
        return IntradaySearchSpace(tf="5m", seed=cfg.seed)
    if cfg.kind == "intraday_15m":
        return IntradaySearchSpace(tf="15m", seed=cfg.seed)
    raise ValueError(f"unknown discovery kind: {cfg.kind}")


# ─────────────────────────────────────────────────────────────────────
# Per-candidate scoring (used by both random and GA modes)
# ─────────────────────────────────────────────────────────────────────


def _evaluate_candidate_across_universe(
    strategy: Strategy,
    bars_by_symbol: Dict[str, Any],
    *,
    initial_capital: float,
    walk_forward_folds: int = 0,
) -> AggregateScore:
    """Backtest one Strategy across all symbols + (optionally) walk-forward.

    The walk-forward stability penalty bleeds into the mean_score so the
    GA's elitism naturally prefers candidates that hold up across time
    windows over ones that crushed the in-sample but might be over-fit.
    """
    per_symbol: List[CandidateScore] = []
    for symbol, bars in bars_by_symbol.items():
        per_symbol.append(evaluate_candidate(
            strategy, bars, symbol=symbol, initial_capital=initial_capital,
        ))

    scores = [s.score for s in per_symbol if s.error is None]
    sharpes = [s.sharpe for s in per_symbol if s.error is None and s.trade_count > 0]
    dds = [s.max_drawdown_pct for s in per_symbol if s.error is None]
    wins = [s.win_rate for s in per_symbol if s.error is None and s.trade_count > 0]
    total_trades = sum(s.trade_count for s in per_symbol)
    viable = sum(1 for s in per_symbol if s.viable)

    mean_score = statistics.mean(scores) if scores else -1e9

    # Walk-forward — only run when requested AND the strategy actually
    # traded on the full window (avoids paying the fold-backtest cost
    # for clearly-broken candidates).
    walk_forward: List[Dict[str, Any]] = []
    stability = 0.0
    if walk_forward_folds > 1 and total_trades > 0 and per_symbol:
        # Run WF on the best-performing symbol — gives the cleanest signal.
        top = max(per_symbol, key=lambda s: s.trade_count)
        top_symbol = next(
            (sym for sym, _ in bars_by_symbol.items()
             if sym == top.label.split(" ", 1)[0] or True),
            None,
        )
        # Find the symbol name from the per_symbol list ordering
        for i, (sym, bars) in enumerate(bars_by_symbol.items()):
            if i < len(per_symbol) and per_symbol[i] is top:
                top_symbol = sym
                break
        if top_symbol:
            folds = score_walk_forward(
                strategy, bars_by_symbol[top_symbol],
                symbol=top_symbol, n_folds=walk_forward_folds,
                initial_capital=initial_capital,
            )
            walk_forward = [f.to_dict() for f in folds]
            stability = stability_score(folds)
            # Blend stability into the composite mean_score so GA selects
            # for robustness. Weight is small but consequential — a strat
            # with 1.0 Sharpe + 0.3 stability beats 1.3 Sharpe + -0.2.
            mean_score = mean_score + 0.3 * stability

    return AggregateScore(
        candidate_idx=0, strategy=strategy, per_symbol=per_symbol,
        mean_score=mean_score,
        mean_sharpe=statistics.mean(sharpes) if sharpes else 0.0,
        mean_drawdown=statistics.mean(dds) if dds else 0.0,
        mean_win_rate=statistics.mean(wins) if wins else 0.0,
        total_trades=total_trades, viable_symbols=viable,
        walk_forward=walk_forward, stability=stability,
    )


# ─────────────────────────────────────────────────────────────────────
# Persistence
# ─────────────────────────────────────────────────────────────────────


def _persist_candidate(
    sb, agg: AggregateScore, run_id: str, kind: str,
    parent_id: Optional[str] = None,
) -> Optional[str]:
    """Insert one discovered_strategies row, return inserted id."""
    row = agg.to_row(UUID(run_id), kind)
    if parent_id:
        row["parent_id"] = parent_id
    try:
        res = sb.table("discovered_strategies").insert(row).execute()
        return res.data[0]["id"] if res.data else None
    except Exception as e:
        logger.warning("persist candidate failed: %s", e)
        return None


# ─────────────────────────────────────────────────────────────────────
# Main entry point
# ─────────────────────────────────────────────────────────────────────


def run_discovery(
    cfg: DiscoveryConfig,
    *,
    triggered_by_user_id: Optional[UUID] = None,
    existing_run_id: Optional[str] = None,
) -> UUID:
    """Run a full discovery batch end-to-end. Returns the run id.

    `existing_run_id` lets a caller (e.g. the REST POST handler) pre-create
    the row to return an id to the user immediately, then hand it to the
    background worker which updates that row instead of creating a new one.
    """
    sb = get_supabase_admin()
    t0 = time.time()

    # 1. Create or update run row
    if existing_run_id:
        run_id_str = existing_run_id
        sb.table("strategy_search_runs").update({
            "status": "running",
            "started_at": datetime.now(timezone.utc).isoformat(),
            "config": cfg.to_dict(),
        }).eq("id", run_id_str).execute()
    else:
        run_row = {
            "kind": cfg.kind,
            "config": cfg.to_dict(),
            "status": "running",
            "started_at": datetime.now(timezone.utc).isoformat(),
            "triggered_by_user_id": str(triggered_by_user_id) if triggered_by_user_id else None,
        }
        res = sb.table("strategy_search_runs").insert(run_row).execute()
        run_id_str = res.data[0]["id"]

    run_id = UUID(run_id_str)
    logger.info(
        "discovery run %s started: kind=%s mode=%s",
        run_id, cfg.kind, cfg.mode,
    )

    # Maps Strategy.name → inserted candidate id, so the GA can record
    # parent_id on children using the parent_label string returned by GA.
    name_to_id: Dict[str, str] = {}
    inserted_rows: List[Tuple[str, AggregateScore]] = []

    try:
        # 2. Resolve + fetch symbols (interval depends on the kind:
        # daily for swing/position/F&O, 5m/15m for intraday)
        symbols = _resolve_symbols(cfg)
        interval = _kind_interval(cfg.kind)
        period = _kind_default_period(cfg.kind, cfg.history_period)
        # Intraday needs more bars per symbol (1 trading day = 75 bars at 5m)
        # so the min-bar threshold is much higher there.
        min_bars = 200 if interval in ("5m", "15m") else 100
        logger.info(
            "run %s — fetching %s bars (period=%s) for %d symbols",
            run_id, interval, period, len(symbols),
        )
        bars_by_symbol: Dict[str, Any] = {}
        with ThreadPoolExecutor(max_workers=cfg.max_workers) as ex:
            futs = {
                ex.submit(_fetch_bars_cached, s, period, interval): s
                for s in symbols
            }
            for fut in as_completed(futs):
                s = futs[fut]
                df = fut.result()
                if df is not None and len(df) >= min_bars:
                    bars_by_symbol[s] = df

        if not bars_by_symbol:
            raise RuntimeError("no symbols returned usable history — aborting run")

        logger.info(
            "run %s — bars ready for %d/%d symbols",
            run_id, len(bars_by_symbol), len(symbols),
        )

        # 3. Search
        space = _build_space(cfg)

        # Scorer used by both random + GA paths
        def _score(strategy: Strategy) -> Tuple[AggregateScore, float]:
            """Returns (full AggregateScore, comparable_score) — full is
            kept so we can persist later, but only the float is used for
            ranking."""
            agg = _evaluate_candidate_across_universe(
                strategy, bars_by_symbol,
                initial_capital=cfg.initial_capital,
                walk_forward_folds=cfg.walk_forward_folds,
            )
            return agg, agg.mean_score

        if cfg.mode == "ga":
            # Persist each candidate as it's scored so the UI can poll
            # mid-run. The GA fires `on_candidate` per evaluation.
            def _on_cand(strategy, _score_val, generation, parent_label):
                agg, _ = _score_cache.pop(strategy.name)
                agg.generation = generation
                agg.parent_label = parent_label
                parent_id = name_to_id.get(parent_label) if parent_label else None
                cand_id = _persist_candidate(sb, agg, run_id_str, cfg.kind, parent_id=parent_id)
                if cand_id:
                    name_to_id[strategy.name] = cand_id
                    inserted_rows.append((cand_id, agg))

            # `evolve` only calls `score_fn(strategy) -> float`. We need
            # the full AggregateScore for persistence, so cache it.
            _score_cache: Dict[str, Tuple[AggregateScore, float]] = {}

            def _score_for_ga(strategy: Strategy) -> float:
                agg, comp = _score(strategy)
                _score_cache[strategy.name] = (agg, comp)
                return comp

            ga_cfg = GAConfig(
                pop_size=cfg.ga_pop_size,
                generations=cfg.ga_generations,
                elite=cfg.ga_elite,
                children_per_elite=cfg.ga_children_per_elite,
            )
            evolve(space, _score_for_ga, config=ga_cfg, on_candidate=_on_cand)

        else:
            # mode == 'random' — sample N, evaluate, persist.
            for i in range(cfg.sample_size):
                try:
                    cand = space.sample(i)
                except Exception as e:
                    logger.warning("sample #%d failed: %s", i, e)
                    continue
                agg, _ = _score(cand)
                agg.generation = 0
                cand_id = _persist_candidate(sb, agg, run_id_str, cfg.kind)
                if cand_id:
                    inserted_rows.append((cand_id, agg))

        logger.info("run %s — persisted %d candidate rows", run_id, len(inserted_rows))

        # 4. Update run aggregates
        viable_total = sum(1 for _, agg in inserted_rows if agg.viable_symbols >= 2)
        best_pair = max(inserted_rows, key=lambda p: p[1].mean_score, default=None)
        sb.table("strategy_search_runs").update({
            "status": "completed",
            "completed_at": datetime.now(timezone.utc).isoformat(),
            "candidates_total": len(inserted_rows),
            "candidates_viable": viable_total,
            "best_score": round(best_pair[1].mean_score, 6) if best_pair else None,
            "best_candidate_id": best_pair[0] if best_pair else None,
        }).eq("id", run_id_str).execute()

        logger.info(
            "discovery run %s completed in %.1fs: %d candidates, %d viable, best=%.3f",
            run_id, time.time() - t0, len(inserted_rows), viable_total,
            best_pair[1].mean_score if best_pair else 0.0,
        )
        return run_id

    except Exception as e:
        sb.table("strategy_search_runs").update({
            "status": "failed",
            "completed_at": datetime.now(timezone.utc).isoformat(),
            "error": str(e)[:1000],
        }).eq("id", run_id_str).execute()
        logger.exception("discovery run %s FAILED: %s", run_id, e)
        raise
